# Дорога на Лену {#Lena}

## 1.09.1992 г. вторник

В 7.00 подъём. 
Позавтракал. 
Уборку сделал. Подтянул спицы. Собрался. Готов. 
Морочно сегодня что-то. Сыровато. 
Смазал педаль. 
Вышло солнце. 
Утром Валентина  Михайловна предложила довезти до Хандыги из хороших побуждений, но я вежливо отказался. 
Пока велосипед едет и выдерживает, хотя багажники не выдерживают. Тряска на дороге сварку просто рвёт и ломает металл.

В 11.40 выезд. 
Выехал с посёлка и сразу препятствие - река, но есть мост. Ещё действует. Деревянный, добротно сделан, но по весне, при разливах поток не жалеет никого и ничто на своём пути. 
Вчера, когда подъезжал к посёлку, слева что-то белело. 
Это была наледь! Она даже летом не растаяла. Это место самое северное по широте, где я проеду до самого Таллина. 
Летом, когда гнус доканает оленей, то они спасаются в спасительной прохладе. 
Сейчас уже сентябрь, наледь уже никак не растает. Пришли первые морозы.  

Проехал мост и мне налево.  
Тут развилка.  
Направо дорога на Усть-Неру. Но там есть участок нехорошей дороги и мост необходимо построить. Летом проблема, а вот зимой, если поддерживают дорогу в надлежащем порядке, то как по асфальту едешь.   
Значит мне налево.   
Рядом с развилкой старое кладбище.   
Слева показались олени, бредут тихонько. Это дикие, на них охота разрешена, а вот есть, которые в загонах, фермерские -- вот их трогать нельзя. Отвечать придётся по закону.   

Нахожусь в Оймяконском районе -- центр пгт. Усть-Нера, а въезжаю в Томпонский район -- пгт. Хандыга.   
На границе районов стоит метеостанция «Восточная».   
Здесь ещё один водораздел.   
И разница с Магаданом уже 2 часа. Поближе к Москве!   

Вот и метеостанция, которая расположена на приподнятой вовышенности.  
Великолепный вид открывается на все четыре стороны.   
Собаки лают. Встречают.  
Вот и начальник станции вышел.   

Поприветствовали друг друга и представились.   
Его зовут Сергей Васильевич Логинов.   
Пригласил в жилище и угостил олениной и замечательным бульоном. 
Сергей предложил остаться на ночлег.   
Заманчиво. Остаться можно было бы, но ехать надо. Погода стоит хорошая, а что ещё меня ждёт? Да и световой день не кончился, продвинуться ближе к Хандыге надо.   
Тогда Сергей посоветовал остановиться у дорожников, которые стоят не так уж и далеко, на 247 км, и у них там вагончики стоят.   
Есть вариант добраться до следующей метеостанции «Западной» и передать привет другому Сергею, который там дежурит.   
А до Развилки далеко, она за метеостанцией.  

Сергей дежурит один.   
У него есть три волкодава, которые отнеслись ко мне благосклонно: не разорвали. Даже дали себя погладить.   
Дуют часто ветра.   
Хлеб и продукты привозят.   
Выходить на связь надо через три часа и давать сводку.   

Переговаривается с «Западной».   
Сергей дал бинокль и я осмотрел окрестности.   
Видно, как пасутся олени.   
В 10 км забойный пункт.   
Слева озеро, там утки плавают. А дальше видны сопки, на которых иногда можно увидеть баранов.   
Тогда Сергей берёт свой карабин и идёт за свежим мясом. Здесь, в комнате есть трофейные рога.   

Но вот пришло время покинуть это прекрасное, красивое место. 
Загадал про себя, что когда-нибудь я приеду ещё сюда.  

Пожали друг другу руки, а затем и с собачками распрощался.   

Поехал бодро, с приятными впечатлениями от встречи.   

> _Хорошие люди в нашей стране живут. Достойно выполняют свой долг. Работают вдали от цивилизации, лишены многих удобств, но не ноют, не сожалеют. Сильные духом люди. А здесь хлюпики и не выдержали бы 
Оглянулся, далеко уехал, но виден ещё домик на холмике.  
До свидания, тёзка. До свидания, Сергей!_

Проехал несколько интересных мест, которые имеют свои названия: «тёщин язык», «заячья губа», «вороний камень».  
Вот и тот мост, который ремонтируют.   
Слева вагончики стоят.   
Вот двух дорожников увидел, а остальные завтра утром с Хандыги приедут.   
Познакомились.   
Одного Виктором, а другого Анатолием зовут.   
Сразу предложили чаю и хариусов отведать.   
Бани, как таковой, нет, но есть будочка опоясанная полиэтиленом с душем.  
В этой импровизированной бане я и принял водные процедуры.   

Мест свободных было много, сказали выбирай любое.   
Расположился.  
Сделал записи и приготовился ко сну.   
А у Анатолия вдруг зуб разболелся.   
Вот бедняга дёргался всю ночь.   
Я то с дороги, сразу почти уснул.  

**_За день -- 74 км. Ок -- 1124 км_**  

## 2.09.1992 г. среда

Встал в 7.30 по-магаданскому времени, а по-местному в 5.30. 
Выехал сразу.

Красивые места, глухие. Машин нет. 
Справа быстрая, горная, чистая река. 
Отвесные скалы. 
По горочкам «американским» поехал. 
Успеваю со спуска поддержать скорость и взлететь на новый гребень, а за ним опять спуск пошёл. Только крути! Не расслабляйся!

На 187 км заброшенные бараки, здесь выселенные строили дорогу. 
Гулаговские места. 
А вот и прижим с петлёй -«Чёрным» зовётся или «Чёрная пасть». 

Подъём около 3 км. 
Если зимой обледенеет, то серьёзную опасность представляет этот участок. Внизу уже один «кольмар» лежит. 
А по мере движения вверх, слева столик опять стоит - в память. 
Внизу шумит быстрая речка лазурного цвета, а вверху над ней, подальше от прижима, мостик висячий маячит. 
Романтическая картинка, но суровая. 

Вот и вершина. 
Поставил велосипед у большого камня, а сам вернулся к прижиму, чтобы ещё раз полюбоваться творением природы. 

Перевёл дух, отдохнул и на спуск. 
Но на спуске справа метеостанция «Западная». 
На часах 11.00 местного. 
Заехал. 

Встретила меня дружная семья Арменова Сергея Александровича с женой и сыном Денисом. 
После знакомства Сергей спросил, желаю ли я перекусить? 
Я ответил, что не откажусь от чая. 
> **tip**
Сергей спросил меня не зря. 
Проезжал здесь на велосипеде Павел Конюхов с другом, брат знаменитого Фёдора Конюхова. 
Тогда Павел категорически отказался от пищи, они использовали только подножий корм в путешествии.

Сергей угостил меня великолепным приготовленным супом. 
В дорогу дал мне сгущёнку и тушёнку. 
Я поблагодарил за гостеприимство и необходимые в дороге подарки. 
В журнале у меня появилась печать ещё одной метеостанции «Западной».

На этом мы расстались с семьёй Сергея. 
Я продолжил спуск. 

14.30, до Тёплого Ключа примерно 100 км. 

Проехал «Белый» прижим, некоторые называют его «жёлтым» из-за цвета песка. 
Вдруг камазы появились. На встречу мчались, как на пожар. Это дорожники. 
Так неслись, что некоторые зайчики не успевали с дороги убежать и попадали под колёса. Много подавленных было. 
Некоторые ещё раненые шевелились. Тут я подобрал одного на обед. 

Проехал посёлок «Развилка». 
Опять оторвался багажник. 
Ремонтирую. Сколько времени у меня это отнимает.

Вот появилась долина. 
Вышел я с горной системы. 
На 140 км появились ёлочки! Растут. Климат изменился. 

На 133 км опять багажник отвалился. 
Закрепил. 
Попил чаю с хлебом и баклажанной икрой. 
Осталось 42 км. Марафон.

В 20.30 приехал в Тёплый Ключ. 
Нашёл ЛТЦ. 
Темно. 
Дежурные по ЛТЦ направили к начальнику. 
Стучусь, дома жена начальника Тамара Александровна. 
Объяснил ситуацию. 
Она взяла ключи и открыла мне комнату в общежитии. 
Очень грязно, через окно бомжи залезают и устраивают попойки. 

Помылся, приборку сделал в комнате, постирался. 
После начал готовить ужин. 
Снял шкуру с зайчика, выпотрошил и картошечкой сварил супчик. 
Бульон получился неплохой.
> **info** 
За день - 177 км. Ок - 1301 км

## 3.09.1992 г. четверг

Встал в 7.00 местного времени. 
Позавтракал, ещё вчерашняя зайчатина осталась. 
Теперь надо заняться ремонтом багажника.

Пошёл искать мастерские. 
Повстречался мужчина, с рыжеватым волосами. 
Познакомились, его звать Никитенко Владислав, он с Кюбюме, которое я уже проехал. 
> **tip**
Некоторые при встрече с ним так и зовут «Рыжий Славка». Он заядлый охотник, рыболов, пишет стихи. Любитель природы. 
Звал меня в тайгу, на охоту. 
Я охотно бы отправился с ним в тайгу, но сейчас у меня другие планы и проблемы, в которые и посвятил его.

Слава охотно принял участие в желании помочь мне. 
Пошли в сварочный цех к его знакомому Геннадию. Там мне заварили проблемные места на багажнике и мой конь снова готов к бою. 
Поблагодарил всех и отправился на обед. 

Сбегал в бухгалтерию и поставили печать - территориального производственного объединения международных связей и телевидения № 18.

До Хандыги 72 км осталось. 
При хорошей погоде и отличном покрытии можно не напрягаясь за 3,5 часа проехать.

Собрался и в 13.20 выехал. 
Дорога отвратительная: крупный гравий, трясёт ужасно. Руки немеют быстро, все отбил. 
Скорость 15 км/час. 
И очень скучно и монотонно тянется дорога. Ровная, без холмиков. 

Через 65 км остановился, чтобы перекусить. 

Только в 18.45 прибыл в Хандыгу, потратил 5часов и 25 минут.

Поехал в поссовет, но там уже нет никого. 
Глава администрации Протопопов Ефим Егорович в Москве. 
Дали номер телефона. 
Заехал на почту, затем по магазинам за продуктами. 
Две буханки хлеба - 20 рублей, масло - 27 рублей, молоко - 10 рублей и конфет на 60 рублей купил. 

Отправился в общежитие автобазы. 
Там я встретился с дальнобойщиком Николаем, с которым мы пересеклись на трассе, на 247 км у дорожников. 
Здесь мы разместились на втором этаже в комнате №20.

Принял душ, постирался, поужинал. 
Зашил куртку. 
Какой маленький участок нудной и плохой дороги проехал, а как вымотался. 
> **tip**
Сделал такой вывод: пусть самая плохая дорога сейчас перед тобой, но и она когда-нибудь, да кончится! 
И ещё: это для того такие дороги, чтобы интерес к жизни не остывал.

Очень устал
> **info**
За день - 72 км. Ок - 1373 км

## 4.09.1992 г. пятница

Встал в 7.00. 
Позавтракал. 
Тут и Николай проснулся.

Отправился в поселковый совет. 
Там меня принял первый заместитель - Юрий Николаевич Иванников. 
Он пояснил, как мне лучше переправиться через Алдан в Усть-Тату. 
Помог с размещением, связался с человеком, отвечающим за спорт и направил в спортзал. 
А в дневнике написал: «Лыжин С.А. прошёл Хандыгу. 4-го сентября 1992 года». Поблагодарил и отправился в спортзал.

В спортзале познакомился с Евгением, который отвечает за спортзал. Разместился в его кабинете. 
После размещения пошли в баню. 
Это моя третья баня.

В бане повстречался с кочегаром Анатолием, который видел меня в магазине №12. Запомнил, нового человека сразу видно. 
Пропарились хорошо, а жажду утолили ароматным чаем. 
После бани мы с Женей отправились в спортзал.

В спортзале я познакомился ещё с интересным человеком - Кондриенко Геннадием, он занимается атлетизмом. 
Есть у него свой тренажёрный зал, который он сам оборудовал и содержит в прекрасном состоянии. 
На стенах в большом количестве висят цветные афиши, посвящённые атлетизму в нашей стране и мире, с чемпионами мира и Европы. 
При знакомстве Геннадий сразу угостил меня шоколадкой «Алёнка».

Геннадий коротко ознакомил меня с залом и окрестностями спортивного городка. 

В 15.00 Евгений пригласил меня к себе  пообедать. Он живёт рядом, на улице Геологов. 
После обеда я отправился гулять по посёлку.

Во-первых, сходил на главпочтамт. 
Позвонил в ГОВД г. Магадана. 
Дозвонился до Паши Бабкина и сообщил, у меня полный порядок и жду переправу через Алдан. 
Далее, по цепочке, Паша передаст эту новость всем моим друзьям.

После направился к пристани. 
Нашёл диспечера. 
Узнал от него , что завтра ракеты не будет, только послезавтра.

Отправился в спортзал. 
Там пообщался с атлетами и единомышленниками по спорту.

Вечером в спортзал зашёл Валерий, который только что прилетел с Якутска. 
Он председатель спорткомитета посёлка Хандыга. 
После нашей беседы с ним, он презентовал мне багажник и велосипедное колесо. Всё это мне очень необходимо и прибыло в нужное время. 
Поблагодарил и мы все сфотографировались на память. 
Геннадий был рядом и в свою очередь дал мне ценный пакет в дорогу. Содержимое пакета состояло из глюкозы, дополнительного спортивного питания и 11 шоколадок. 

В кабинете, где я разместился, был телевизор, так что я был в курсе всех новостей. 

Уснул в 1.00, просыпался в 4.00 , 6.00. 
Писал, читал, пил чай, слушал радио.

## 5.09.1992 г. суббота

Встал в 8.30. 
Решил узнать, каким способом можно ещё перебраться на тот берег. Может быть есть катера или баржи проходящие. 
Время жалко и погода стоит великолепная: солнечная и без ветра. 
Сел на велосипед и поехал к пристани. 

Опять стал пытать диспетчера, как перебраться на тот берег. 
Он послал меня в затон. 
В затоне узнал, что на другом берегу есть судно. 
На катере переправился на тот берег. 
Там на якоре стояло судно "Клязьма" с баржей, но стоять они будут ещё долго. 
Обратно переправился и поехал до спортзала. 
Неудачная попытка. 
Придётся завтра утром на ракете переправиться до Усть-Таты. 

Заехал в магазин и купил 2 литра молока и буханку хлеба.

После обеда поспал два часа. 
По телевизору шёл фильм «Терминатор». 
Подшивал куртку и другую одежду. 
Уснул в 1.00

## 6.09.1992 г. воскресенье

Встал в 4.15 и сразу на пристань. 
Ещё темновато. Народу многовато, но билет достал. 
Купил за 364 рубля, сбор - 8 рублей и багаж - 86 р. 
Прохладно, по реке стелится туман.

Ровно в 6.00 отчалили. 
На следующей пристани стояли 30 минут из-за тумана. 
В салоне было тепло и через некоторое время  я уснул. 
Встал через два часа. Вышел на корму. Туман рассеялся, солнце ярко светит.
Хороший день, только и крутить педали. 
Река Алдан широкая, чистая, с высокими берегами, на которых растёт лиственница, берёза, ель. 
Всё пожелтело - золотая осень. 

11.30 - Усть-Татта. 
Моя пристань. 
Вышел. Поднялся на высокий берег. 
Проверил аммуницию, поддтянул багаж и поехал по посёлку. 
Улица вывела меня на трассу, которая привела меня в посёлок Уолба. 

В посёлке имени П.Алексеева, революционера, решил перекусить. 
Места очень красивые: поля чередуются с берёзовыми рощами. 
Встречаются коновязы, которые устанавливают в честь праздника, юбилея или важного события. 
Свободно гуляют коровы. 

Дорога сухая, твёрдый грунт. 
Мне просто повезло, а если был бы дождь, то дорогу развезло и было бы скользко, грязь и лужи. Передвигаться было бы проблемно, а мне это не надо.

Через 55 км на дороге одинокая изба стоит. 
Подъехал, на памятной доске прочитал: «Здесь 1883-1890г.г. жил Ионов Всеволод Михайлович, этнограф, педагог(политссыльный)».

Еду, а левая педаль партачить начинает, клинит. 
Подремонтировал. 
За 12 км до посёлка сорвалась резьба на правой педальке. 
Опять ремонт.

За 8 км до Ытык-Кюель догнал меня мотоциклист с коляской. 
Остановился и поинтересовался куда я еду. 
Предложил мне доехать до Ытык-Кюель и переночевать у его родственников. Согласился. 
Он поехал и обещал встретить в посёлке. Я поехал за ним.

В 18.40 въехал в посёлок. 
Еду по главной улице и вижу, стоит мотоциклист и машет мне рукой. 
Подъехал и последовал за моим гостеприимным доброжелателем. 
Остановились у дома. 
Представился - Большаков Василий Егорович.

Зашли в дом. 
Василий представил меня хозяйке - Нине Ивановне Саввиной. 
Она сразу же мне доложила, что была в Таллине по туристической путёвке и ей очень понравилось. 
Василий, как приехал затопил баньку. 
Пока вели беседу, расспрашивали друг друга за ужином, «подошла» и банька.

Мы пошли первыми с Василием Егоровичем. 
Он тоже любитель похлестаться в баньке. 
Друг друга отпарили, как следует и вышли молодыми и просветлёнными.

После нас пошли в баню женщины, а мы сели за стол чаёвничать. 
И тут я удивился действию Василия. Он предложил после баньки пропустить по рюмочке. 
Я согласился. 
Он налил стопку и открыл печь, где полыхал жаркий огонь. Ловко и резко выплеснул  содержимое в печь со словами: «Чтобы ты доехал до конца!», а из печки моментально выскочил огненный язычок. 
Тут же заполнил стопку и произнёс  тост: «А теперь за встречу, за знакомство, за баню!»

Посёлок Ытык-Кюель переводится как «Священное озеро», пояснил мне Василий Егорович. 
Сам же он является главой администрации Уолбинского села. 
Эта была моя четвёртая баня.

Вернулись женщины с бани и продолжился наш живой разговор. 
Нина Ивановна поинтересовалась: «Какой сейчас курс валюты в Таллине, сколько вещей можно провозить через границу?»
И на последок дала свой домашний адрес.
> **info**
За день - 85 км. Ок. - 1458 км

## 7.09.1992 г. понедельник

Встали позавтракали и поехали с Василием Егоровичем на мотоцикле по посёлку. 
Он хочет мне показать достопримечательности посёлка. 
Сначала поехали в парк, там и стадион есть. 
Это место массовых гуляний. 
Много в этом парке коновязов, посвящённых различным юбилеям, памятным датам, событиям. Есть коновяз, посвящённый юбилею - 40 летию электрификации страны, Якутской АССР. 
На одном коновязе был нарисован Иосиф Виссарионович Сталин в цвете. И, что удивило меня, никто не глумится над созданным.

Вернулись домой на улицу Кочкина. 
Нина Ивановна угостила сдобой, попили чаю, а в дорогу дала огурцов, помидор.
Поблагодарил и стал собираться.

Я в свою очередь проводил Василия Егоровича до больницы. 
Сам в поссовет. Там помошник главы посёлка (Д.Петров) принял меня и сделал отметку в журнале.

Рядом с поссоветом тянется аллея, где расположились портреты тех, кто погиб в Великой отечественной войне и трудился в тылу. Фотографии все цветные и качественные. Обошёл всю аллею.

Вернулся к велосипеду и отправился по намеченному маршруту на Чурапчу.

Когда подъезжал к посёлку Кыйы, из леса выбежали на лужайку пионеры, лет 10-ти. Появился преподаватель. 
Я спешился и направился к учителю. 
Оказывается я попал на урок физкультуры. 
Физкультурника попросил сфотографировать меня с учениками и передал ему фотоаппарат. 
Ребятам дал команду и они быстро построились, как я просил, в две ширенги. Школьники очень дисциплинированные оказались и получилось великолепное фото на долгую память. 
Вот только на физкультуре они были в школьной форме и в галстуках. Поблагодарил и помахав рукой поехал дальше.

До Чурапчи ещё один раз перекусил. 
Идёт ремонт дороги.

> **tip**
Ещё случай был. 
Еду и вижу: в кювете лежат два якута, а мотоцикл перевёрнутый.  
Думаю помощь нужна, остановился, присмотрелся. 
Живые и шевелятся. 
К ним поспешил. 
А в ответ пьяный голос: «Держи его, у него и велосипед есть.» 
Один уже встал и поковылял в мою сторону. 
Я вернулся к велосипеду, поднял его и начал рагонять велосипед. 
Сел и что есть мочи стал крутить педали. 
Так я оторвался от хулиганов-алкоголиков. 
Да, не хотел бы я лишиться здесь своей «перламутровой девятки».

Въехал в посёлок Чурапча. 
Доехал до столовой. 
Хотел поставить к крыльцу велосипед, но тут подошли шесть парней и устроили допрос.

«Откуда едешь русич?»
«С Магадана»? - ответил я.
«А где границу и таможню пересекал?»
«Там, где пересекал, никакой таможни нет.» - пояснил я.
«Ладно, иди ешь, потом поговорим?!»

После таких слов я взял велосипед под рога и с ним вьехал в столовую.

Поел на 44 рубля. Когда ел, ко мне подсел парень, якут. 
«Откуда?» - спросил он.
Ответил и спросил: «А почему у вас ребята такие агрессивные?»
«Какие?», - вомущённо спрашивает он.
«А вон, у столовой стоят», - показал я и рассказал о произошедшей ситуации.

Парень вышел, подошёл к «молодой шестёрке», что-то сказал и вернулся.

«Эти тебя не тронут, а где будешь ночевать?» - отрапортовал парень.

И в дальнейшем просил ехать и никуда не поворачивать и не разговаривать по пути. Проехать эти места. 
Причина проста: здесь  много чемпионов мира и Европы по различным видам единоборства. Носы всем местным побили, поэтому ищут тех, с кем ещё можно потягаться. 
Я только спросил: « Где здесь милиция?»
«Она рядом со столовой», - И указал где.
Я вышел со столовой, сел на велосипед и покатил в райотдел, а ребята молча стояли в круге.

В 17.10 зашёл в райотдел. 
Меня встретил дежурный инспектор Бараньков Г.Н. 
Объяснил ситуацию и спросил, где можно купить хлеба. 
Гера послал меня в пекарню, там в 18.00 будут давать горячий хлеб.

Отправился к пекарне. Там небольшая очередь. 
Дождался, купил две буханки за 28 рублей. 
Назад уже возвращался по параллельной улице. 
Выхожу на перекрёсток. 
До милиции 500 метров. Но что я вижу. 
Двое хулиганов останавливают дальнебойщика и начинают трясти водителя. 
Просят его выйти из машины, а тут вторая фура подходит. 
Её тоже просят остановиться, но уже впереди этой. 
А заметив меня, один хулиган машет мне и кричит: «Стой!» 
Дело швах. 
Пока вторая фура медленно объезжала первую я прикрываясь ею рванул к райотделу. 
Бегу, прижав буханки хлеба к груди. 
И тут в след слышу: «Держи его!»
Я бегу, сколько могу перебираю ноги, не оглядываюсь. 
Ноги становятся чугунными. Хлеб чуть не выронил.

Запыхавшись, влетаю в райотдел. 
Кричу: «Грабят! Рэкет!»
Дежурный наряд вместе со мной в машину и на то место, где это произошло.

Машин нет. Рэкитиров нет. 
Начали объезжать близлежащие улицы. 
Изъездили всё, как след простыл. 

Я обрисовал одного: составил словестный портрет. Характерные черты, движения, а так же в чём были одеты. 
Дежурный, заместитель по оперативной работе, сразу просиял. 
Узнал этих хулиганов-рэкетиров. 
И мы поехали в райотдел.
Познакомился с замом по оперработе поближе. 
Это Алексеев Геннадий. 
Он тоже занимался спортом, бегал марафон «Дорога жизни» в Ленинграде, только 20 км.
Геннадий предложил мне поужинать с ним дома. 
Я предложение принял и мы поехали к нему домой.

Дома он познакомил меня с женой и детьми. 
Рассказал он мне про специфическую жизнь в здешних местах. 
Здесь нет водопровода, так как вечная мерзлота. 
Если мы заготовляем грибы и ягоды, то здесь заготовляют ещё и лёд. 
На чистых озёрах нарезают кубы льда доставляют в ледняки на хранение. Лёд есть «технический» и «питьевой», последний для употребления в пищу. 
Я захотел было попить и подошёл к бочке с водой, а Геннадий остановил меня и показал бочку с питьевой водой. 
Больно чистой смотрится. 
Из неё и супы варят и чай пьют. 
А «техническая» водичка для остальных нужд - стирка, мойка, полив.

Поблагодарил за ужин и Геннадий отвёз меня в РОВД. 
Он тоже посоветовал встать пораньше и не заворачивать в посёлки. 
Ехать и не включаться в разговоры с сомнительными людьми.

Спал в подсобном помещении дежурной части. 
Было не очень уютно, но не на улице и под охраной. 
Ещё мешок с сюрпризом под лавкой был. 
Лежал и спал, а ночью мешок зашевелился. 
Вот перепугался. Там оказывается поросёнок был. 
Считаю я в лучшем положении был. 

Ну и денёк мне выдался: одни приключения и неудобства. 
Беспокойная ночь была. 
А хрюшу жалко.

> **info**
За день - 92 км. Ок. - 1550 км

## 8.09.1992 г. вторник

Встал в 4.00. 
Вернее, не могу спать, когда  невинная скотинка страдает. 
Ворочается, похрюкивает в мешке. Неволя одно слово.

Тихонько вышел с РОВД и поехал по безлюдным улицам. 
Выехал на трассу и решил ехать до самой Лены, до Нижнего Бестяха. 
Бестях перводится как «сосна», «сосновый».

Дорога гравийная, но ехать можно. 
Солнышко поднимается. Стало веселее ехать. 
Проехал Маралайы и Нуорагану, не сворачивал, как советовали. 

С 12.00-13.00 обед прямо на трассе.

15.00  подъезжаю к Тюнгюлю. 
> **tip**
Навстречу мужик идёт, поравнялись и спрашивает: «Закурить не найдётся?»
Отрицательно помотал головой, а про себя подумал: «Вот мне ещё сигарету в зубы и попыхивать ехать!» 
Или велогонщики едут и у всех сигареты в зубах? 
Или гребцы, пловцы, борцы с сигарой? 
Смешно.

15.15 Тюнгюлю. 
Вижу столовую справа. 
> **tip**
Подъезжаю, вот думаю сейчас поем, проголодался очень. 
Обед у них. Отказали. 
Как же так, обеденное время у людей и они в это же время уходят тоже на обед. Вроде нонсенс. Ждать не стал. 

Зашёл в соседнюю контору, попросил воды. Дали и поехал дальше к великой реке Лене.

За 25 км до Бестяха появились сосенки. 
Вот появилась река с островами. 
Добрался. 
На часах 20.15. 
Устал. 
Ехал по гравию и отбил все ладони. 

По главной дороге еду и увидел справа  ПОМ (поселковое отделение милиции). 
Спешился и в дежурку. 
Обратился к дежурному старшему сержанту милиции Михайлову М.М., который поставил мне печать Н.-Бестяхского ПОМ, М-Кангаласского района. 
Дежурный инспектор Павлов тоже оставил свою отметку в журнале.

Здесь же мне подвернулся на счастье сержант милиции Колесов Иван, инспектор ДПС ГАИ. 
> **tip**
Он мне очень помог с ночлегом и ужином, а со сваркой договорились на завтра. Багажник у меня опять отвалился, левая вилка.
Иван пояснил, как дальше ехать, состояние дорожного покрытия, как никак гаишник. 
Сам он живёт с родителями в Майя - это рядом в 36 км. 
Сегодня он дежурит. Повезло мне. 
Я присмотрелся к нему. 
Он молод, но ведёт себя так, как хотели бы видеть наши граждане своих народных милиционеров. Защитников от всяких хулиганов и тех, кто нарушает общественный порядок. 
Милиционер должен быть внимательным, вежливым, отзывчивым, помочь в трудную минуту любому гражданину, нуждающемуся в этой помощи. 
Всё это есть в Иване. 
Да к тому же он высокий, красивый, аккуратный, чем не пример для подражания!

Помог он мне с ночлегом. Разместил в домике для приезжих, прикомандированных магаданцев. 
Он так и именуется «магаданский уголок».

Я помылся. 
Потом стал готовить ужин. 
В этом тоже помог Иван. 
Дал капусту резаную с рисом и овощами, жир, два яйца, галеты, чай, сахар, хлеб. 

Поужинал и в 1.00 уснул. 
Приснилась одноклассница Ангелина и школьные друзья. 
У них какой то вечер был. 
> **info**
За день 170 км. Ок. - 1720 км

