# На столицу БАМА --- Тынду {#BAM}

## 9.09.1992 г. среда {#BAM-09-09-1992}

Встал в 5.00 и снова лёг до 7.00. 
Чай и хлеб с маслом.

В 8.30 в столовую. 
Поел на 50 рублей. 
На почту. 
Теперь в мастерские, багажник чинить. 
Сварщик Сергей помог очень. Заварили багажник, что впереди у меня и запасной тоже. 
Дядя Федя помог. солярой протёр цепь и посоветовал салидолом больше не смазывать. Цепь беречь. Уже поистёрлась. Только салярой протирать.

В 10.35 приехал в домик №7 после ремонта. 
Чай, сбор и в путь. 

В 11.45 на трассе. 
С Иваном больше не виделись, он после дежурства домой уехал.

Дорога - полный завал! Гравий крупный.

В 16.30 привал на обед. 
60 км проехал.

17.15 в путь. 
Дорога ремонтируется. Есть и хорошие участки. 
Дорожников встретил, посоветовали на ночлег остановиться в Качикатцы заехать, в ДРСУ-6. 

Еду по совету в ДРСУ. 
Встретился с Владимиром Михайловичем, главным инженером. Он дал добро на размещение.

Через вахту нашёл дежурную Раису. Устроила в гостиницу. 
Сварил суп, кашу, чай попил. 
Ванну принял, постирался. 
К администратору гостиницы Голощаповой. 
За гостиницу заплатил 75 рублей. 
Поставили печать в ДРСУ-6: РСФСР, Российский государственный концерн «Росавтодор». 
Сказали, что в 20 км от этого места есть священое место: источник-ключ, чистая вода.

***За день --- 107 км. Ок.--- 1827км***

## 10.09.1992 г. четверг {#BAM-10-09-1992}

В 10.00 я выехал на трассу, в сторону Алданского района.

11.00 доехал до геодезической вышки. 
Забрался. 
В дымке видна река Лена. 
Оставил свой автограф: «Лыжин-Таллин» на поручнях. Фото на память.

Спустился и вновь продолжил свой путь. Дорога сносная, пыльная. Тяжело идёт велосипед.

15.15 «155км» --- привал на обед. 
Направо - граница Алданского района. 
Рядом лежит мотороллер, разобранный на запчасти.
Я тоже поковырялся и набрал болтов и гаек. 
Место красивое, листва жёлтая.

16.15 в путь. 
Грейдер подъехал, дорожники. 
Спросил: «Как дорога дальше?». Обнадёжили, неплохая. 
Тружусь, еду и пою. 
Темнеет. 

Посёлок Добролёт, метеостанция, будет закрываться. 
И на тебе --- стоит лосёнок, а на ошейнике написано: «Маня». 
Сфотографировал Маню и дальше в путь. 

Водитель камаза 49-02 ЯКМ с Алдана, остановил меня. 
Водителя зовут Виктор, напарника Саша. 
Предложили поужинать вместе. 
Не отказываюсь. 
Чакушку перед ужином. 
Ели куру, помидоры, перец, чай.

Спал в кузове на мешках, под тентом, забравшись в спальный мешок.

***За день --- 130 км. Ок. --- 1957 км***

## 11.09.1992 г. пятница {#BAM-11-09-1992}

Проснулся в 6.00. 
Разломался и вылез с кузова. 
Разбудил ребят, перекусили: кура, чай. 

В 8.15 крепкое рукопожатие и пожелание друг другу хорошей дороги. 
Ночевали на 230 км у ручья.

9.20 спустился с сопки в посёлок Улуу.
Одноимённая речка протекает. 
Здесь тоже есть ДРСУ, к которому я сразу подъехал. 
Нашёл сварщика, его звать Артур. 
Ознакомил его с своей проблемой и он охотно помог мне: заварил оторванные части багажника. 
Поблагодарил Артура за внимание и быструю помощь.

В 10.15 открылся магазин, в котором я отоварился на 241 рубль, купив две тушёнки и шоколадки. 
Подремонтировался, отоварился, настроение хорошее и через десять минут я опять в седле.

Вышло солнышко, дело спорится.

12.30 проехал два ручья: Малый и Большой Кырбакит и свернул на привал перекусить.

В 14.20 проехал 290 км, пересёк речку с интересным названием Курун-Кен-Кю и дождь пошёл. Хороший. Промок, но продолжаю ехать. 

Встретил дорожных ремонтников, это водители Иван и Борис. 
Завязался разговор. 
Подсказали, что скоро будет посёлок, где можно остановиться. 
Еду.

В 17.15 показался посёлок Верхняя Амга. 
Въезжаю на мост, перекинувшийся через реку Амга, впадающую в реку Алдан, на котором стоит Хандыга. 

> *Если сплотится по реке, то можно замкнуть круг. 
Интересное путешествие получилось бы. 
Стою на мосту и открывается великолепная картина. 
Просто полный Левитан. 
Краски осени играют на том берегу: лес, как мозаичная картина и ещё освещённая солнцем. 
Кристально чистая река бежит под мостом. 
Просто благодать.* 

Осмотрелся. 
Слева увидел метеостанцию с характерными постройками. 
Мне туда, но придётся вернуться. 
Развернулся на мосту и неспеша поехал к станции.

Встретил меня начальник станции Сергей Путинцев. 
После короткой ознакомительной беседы, он предложил мне поужинать. 
Угостил мясным бульоном.  
За чаем Сергей  рассказал мне о здешних местах, что река Амга нерестовая и вся промышленная деятельность на ней запрещена. 
У станции название тоже интересное: «Буяга», Якутского территориального управления по гидрометеорологии, Алданского района. 
Здесь я и остался на ночлег. 
Перед сном я сходил на речку и окунулся, после чего по телу рапространился прилив тепла. 

Сергей выделил мне место в служебной комнате, где была большая книжная полка и сани, оборудованные под зиму. 
В сани был вшит меховой мешок, как сумка у кенгуру. Забравшись в сумку, как кенгурёнок, я быстро уснул.

***За день --- 102 км. Ок. --- 2059 км***

## 12.09.1992 г. суббота {#BAM-12-09-1992}

Встал в 7.30. 
Выспался. 
Попили с Сергеем чайку, а на дворе полный штиль: туман и идёт моросящий дождь.

Только после обеда смог выехать. 
Проехал 18 километров и внезапно на дорогу выбежали две охотничьи собаки, вероятно, заплутали. 
Преодолеваю очередной подъём. 
За мной колонна машин идёт. 
Я продолжаю движение, но прижался к обочине. 
Водитель первой машины поровнялся со мной, опустил окно и спрашивает: «Откуда едешь?»
«С Магадана», --- ответил я.
«Куда?» --- последовал второй вопрос.
«В Таллин», --- ответил я.

Впереди показалась стоянка. 
Водитель поднажал и стал сворачивать на стоянку, а за ним и вся колонна. 
Теперь я поравнялся  с его машиной. 
Он взмахом руки просит меня остановиться. 
Останавливаюсь. 
Вышли все водители колонны.
Он представился: «Михаил» и протягивает руку. 
Вероятно, он старший и обращается к остальным: «Вот едет парень с Магадана быстрее нас, а мы не можем 150 километров проехать!» 
И тут же даёт указание: «Развести костёр и накормить горячим!» 
Обменялись с ним адресами. 
Приятный, внимательный и неравнодушный человек, всегда готов помочь в дороге. Сын у него в Якутске, тоже милиционер и работает в ГАИ.

Короче накормили, дали в дорогу две тушёнки, сгущёнку, а от остального я отказался, тяжело ехать. 
А предлагали картошку, консервы и прочие продукты.  
Поблагодарил и собрался ехать. 
Но Михаил предложил встретиться в Томмоте и дал адрес, куда они и держат свой путь. 

Продолжаю подъём. 
Водители обходят меня и клаксонят. 
Но тут навстречу спускается с перевала грузовая машина. 
Михаил узнаёт водителя и у них завязывается серъёзный разговор: кто-то кому-то что-то должен. Это надолго, подумал я. 
Тут, действительно, и до Томмота могут не доехать, если вспомнили о долге. 

А вот ещё одна встреча со знакомыми, у которых переночевал два дня тому назад в кузове. 
Виктор и Саша возвращались в Якутск, но уже с картошкой. 
Мы повстречались в таком месте, где ничего не росло и стояли только голенькие лиственницы. 
Оказывается здесь был обширный пожар, тайга. 
Рядом пожарных частей нет. Выгорело очень мого леса. Около 40 км!

За 15 км до Томмота появился асфальт. 
Как приятно ехать по ровной дороге. 
Стемнело. 
Тихо и машин нет. 
Еду и глаза закрываются, дремлю. 
Сильно тряхнуло. 
Это асфальт кончился, гравий пошёл. 
Темно, ничего не видно, что называется - ни зги.

В 22.25 я в Томмоте. 
Ребята меня так и не догнали. 
Но я поехал по адресу, который они мне дали. 
Переехал мост через реку Алдан. 
Свернул на улицу, нашёл дом №32, где мы должны были встретиься, но никто так и не открыл. 

Вернулся на мост. 
Прохожего спросил, где здесь метеостанция расположена. 
Получив ответ, я вернулся на левый берег и проехал вдоль набережной, пока не наткнулся на метеостанцию с названием «Томмот». 
На часах 23.30. 

Постучался. 
Дверь открыл сам начальник - Малько Владимир Алексеевич. 
Коротко обрисовал ситуацию, после чего Владимир Алексеевич принёс раскладушку, спальный мешок и кипятильник.

Смастерил себе ужин, поел, попил и уснул в 1.00.

***За день --- 110 км. Ок. --- 2169 км***

## 13.09.1992 г. воскресение {#BAM-13-09-1992}

С утра шёл дождь. 
На метеостанции дежурит  Павлова Лариса, она гидрогеолог. 
Сотрудница Тамара картошечки с луком принесла. 
Готовлю обед.

Метеостанция «Томмот» находится на левом берегу реки Алдан, за интернатом. 
Пришёл Владимир Алексеевич, чтобы проводить меня. 
Его я попросил сфотографировать меня на фоне Алдана на память. 
Всех поблагодарил за тёплый приём и отправился дальше в путь.

Вновь еду по мосту. 
Рядом построен новый, добротный железнодорожный мост. 
Здесь АЯМ (Амуро-Якутская Магистраль) дальше торит дорогу на Якутск.
Доехал до первой бензоколонки. 
Там помыл велосипед, смазал салярой цепь и в 15.15 уже ехал по трассе.

Пошли затяжные подъёмы и спуски. 
Справа и слева насыпная дорога - это здесь пройдёт будущая железная дорога.

Посёлок Яконит, столовая и магазин не работают. 
Через 40 км перед очередным подъёмом забрался в трубу и там попил холодного чая с хлебом. 
Негде прислониться, то работы идут, то грязь везде. 
Встречаются сопки, поросшие сосняком, елями и лиственницами, но вот появился похоже кедровик и можжевельник.

Карьеры пошли. 
Белазы работают. 
Указатель: поворот на п. Синегорье. 
Проехал Нижний Куранах, затем Верхний Куранах. 
Нижний посовременнее будет, а на повороте направо течёт одноимённая река.

Перед Алданом подъём затяжной. 
В конце слез и один километр прошагал пешком. 
Цепь берегу, уже порядочно стёрлась. Смазал её салярой.

По главной улице спускаюсь в город. 
Доехал до столовой и тут же гостиница для водителей. 
Администратор Софья Михайловна разместила меня в комнате отдыха (красный уголок). 

Принял душ. 
Постирался. Грязи налипло! 
Ужин приготовил. 
По телевизору новости посмотрел. 
Разработал маршрут на завтра.

***За день --- 80 км. Ок. --- 2249 км***

## 14.09.1992 г. понедельник {#BAM-14-09-1992}

Проснулся в 6.00, встал в 6.30. 
Приготовил суп, чаю выпил. 
Зашёл в столовую поел на 42 рубля.
Затем отправился на предприятие «Аямтранса», где мне поставили печать.
Собрался и вышел на дорогу.

Меня встретил встречный ветер и снег с дождём. 
Мерзопакостная погода, но надо ехать.

Проехал 25 км и асфальт кончился. 
Через некоторое время проехал старательскую артель с интересным названием «Юхтинка». 
Появились большие насыпи, а вот и железка. Строится - дорога железная!

Миновал Орочён-2, потом просто Орочён. 
Дорога никакая. 
На железнодорожных путях стоят гружёные вагоны, уголёк подвезли. 
Подъезжая к Большому Нимныру встретил жигулёнка. 
Водитель подал сигнал и тормозит меня. 
Подъехал к нему, а водитель просит спешиться и сесть в машину. 
Дождь-то идёт. 
Думаю, что-то хочет спросить и узнать информацию по состоянию дороги? 
Сел, ответил на вопросы, а в ответ предлагают выпить чакушку вина, покушать горячей картошечки с тушёночкой и запить ароматным горячим кофе! 
Всё было очень вкусно, по-домашнему. 
Что я могу на это ответить? 
Есть в нашей стране добрые и неравнодушные люди! 
Спасибо им! 
Поблагодарил водителя Анатолия, Галину. 
Дал им свой журнал, в котором они отразили свои впечатления, пожелания и оставили свои адреса. 
Это были две семьи: Елисеевых и Иноземцевых. 

Вышел из машины с таким чувством, что готов крутить педали хоть ночью, если будет такая поддержка. 
А столовая была закрыта. 
Всё вовремя получилось и я снова в дороге.

И снег нипочём, всё одолеем. 
Становится холоднее. 
Надел штормовку, штаны, куртку спортивную. 
Ветер усиливается. 

У дорожного знака прислонил велосипед и перекусил. 
Доел ветчину с хлебом, запил холодным чаем. 
Продолжил своё передвижение по скверной дороге. 
Весь в грязи и мокрый. 

Ещё один перекус был на стоянке для машин. 
Везде грязь, негде прислонить велосипед. 
Подъехал к камазу. 
У водителя поинтересовался, сколько он стоять будет и можно ли прислониться к его колесу на минут 30. 
Дал добро. 
Перекусил и поблагодарил водителя отмашкой руки и в путь на Малый Нимныр. 

Уже темно. 
Появились огоньки. 
Это посёлок, но как показаться? Я весь в грязи. 
Справа ручеёк протекает. 
Надо привести себя в порядок. 
Положить велосипед некуда, везде грязь. 
Замажу багажные сумки. Вымыл велосипед. 
Затем нашёл большой камень, прислонил велик и стал быстро раздеваться догола. Быстро выполоскал штаны, носки, выжал сколько было сил и всё одел на себя.  
Неприятно, но надо. Сейчас же в посёлок, там ещё раз постираюсь, высушусь, помоюсь и прогреюсь в горячей воде. 

Слева, при въезде в посёлок, предприятие стоит и автобаза большая. 
Я в диспетчерскую. 
Там женщина дежурит. 
Звать Марией Ивановной. 
Договорился за 70 рублей переночевать до утра. 
Постирался и умылся в холодной воде, а другой нет. 
«А где сушить?», - спросил Марию Ивановну, а в ответ: «Отопления нет!» Завал... 
Я дрожу. 
Она выдала дополнительно два одеяла и матрац. 
Пригласила на чай. 

> *Стал потихоньку отходить, а Мария Ивановна стала жаловаться на нынешнюю жизнь. 
Она тут в одном лице на нескольких должностях. 
Всё забросили и ликвидировали. 
Узнав, что я еду в Таллин через Москву, попросила передать: «Как дальше жить?» 
Здесь Алданское нагорье, ничего не растёт, картошку привозили с Якутска! А сейчас прекратили. Люди уезжают с посёлка. А когда-то здесь жизнь кипела. Вот он результат развала великой страны. Жалкая картина. 
После рассказанного я даже не обращал внимание на то, что нет горячей воды, отопления. 
Есть крыша, что тебе надо. Люди вот как стали жить. 
Что дальше нас ждёт?**

Посмотрели по телевизору новости и в 23.10 я пошёл спать. 
Дал я себе сегодня перцу. 
Тяжёлый участок проехал. 
Молодец! 
Окутался и дрожу. 
Стал активно дышать и нагнетать воздух.

***За день --- 127 км. Ок. --- 2376 км***

## 15.09.1992 г. вторник {#BAM-15-09-1992}

Встал в 10.00. 
Вскипятил чай. 
Снег всю ночь шёл. 

Открылся магазин и я пошёл за продуктами. 
Взял изюм --- 240 руб., две тушёнки --- 120 руб., хлеб --- 10 руб., 4 пачки вафель --- 40 руб., пряники --- 75 руб., конфеты --- 60 руб.

На почту завернул. 
Конверты --- 6 руб. и бандероль родителям в деревню --- 14 рублей.

В диспетчерской перекусил, почистил велосипед, смазал салярой цепь. 
Поблагодарил Марию Ивановну и в путь. На юг.

В 13.15 выехал. 
За Нимныром сразу показался перевал «Тит». Снег на перевале лежит и немало. 
С этой стороны перевал пологий и с южной тоже. Но когда спустился, то удивился, здесь снега нет. 
Приехал в Малые Хатыми. 
Встретил Витю Маркова, водителя камаза. 
Он посоветовал остановиться в ЛТЦ у Малько Василия Николаевича. 

Продолжил свой путь. 
Встретился перегон новых голубеньких жигулей. 
Водитель, остановившись около меня, спросил: «Как проехать до Малого Нимныра». 
Пояснил и получил в награду печенье и килограмм слив.

Горки чаще стали встречаться. 
Дождь пошёл. 
Левая сторона у переднего багажника лопнула. Перевязал. 
Еду. 
Ещё спуск. 
Дождь усиливается. 
Вот и снег повалил. 
Багажник опять ломается. Чиню 45 минут. Время драгоценное теряю. 
В подъем пешком. 
Багажник просто ложится на колесо. 
Остался последний подъём. Справа карьер. Темно. Снег кружит. 

Подъехал еразик. 
Водитель, звать  Владимир, предложил довести до Чульмана, там и подремонтируешься. 

В машине завязался разговор. 
Владимир предложил переночевать у него дома, а завтра отправиться в мастерские. 
Согласился. 
Приехали. 
Я сразу мыться, стираться. 
Поужинали и в час я пошёл спать.

Трудный и тяжёлый денёк.

***За день --- 106 км. Ок. --- 2482 км***

## 16.09.1992 г. среда {#BAM-16-09-1992}

Утром в 10.00 встал. 
Позавтракал. 
Собрался. 
Владимир проводил до дороги, а далее сам дошёл до поссовета. 
Глава администрации А.Серга был на месте. 
Посоветовал сделать ремонт на автобазе №3. 
У Александра взял вязальную стальную проволоку и дальше отправился к начальнику ЛТЦ - Малько Василию Николаевичу, по совету водителя камаза --- Маркова Виктора. 
Устроил за 30 рублей ночь. 
Нормально. 
Забежал в магазин и купил хлеба, масла и две тушёнки на 144 рубля.

Теперь пошёл на автобазу «Якутскзолотоснаба» ремонтировать велик. 
Направили в сварочный цех. 

> *Там был дежурный электрик, которого зовут Пётр Михайлович Серов. Познакомились, рассказал о себе, путешествии и о своей  проблеме.
Он мне очень помог: вместе сделали стяжки для багажника, сварили, кожух смастерили, болтов и гаек дал. 
Принял хорошо! 
Суп вместе сварили, а потом драники с чаем попили. 
Спасибо ему. 
Язык общий быстро нашли. 
Таких бы по-больше встречалось в пути. 
Девиз у Петра Михайловича хороший: «В каждом рисунке должно быть солнце!» 
А кто бы сомневался?*

Он мне начертил и показал дальнейший путь до Большого Невера. 
Обменялись адресами. 
Посоветовал остановиться в Нагорном у знакомых. 
Пришёл в ЛТЦ в 21.30. 
Стирка. 
Собрался и наметил маршрут на завтра. 
Уснул в  00.50

## 17.09.1992 г. четверг {#BAM-17-09-1992}

Встал в 9.00. 
С утра дождь. 
Позавтракал и жду погоды. 

В 12.15 выехал с Чульмана. 
Вновь заморосил дождь. 
Пошли крутые горочки по 1.5 км. Четыре больших подъёма одолел. 
В Серебряном Бору попросил мальчика и он сфотографировал у поворота на Нерюнгри. 
Далее поворот на Беркакит. 
Заехал на пост ГАИ. Там дежурят Александр и Владимир. 
Накормили картошкой с тушёнкой и напоили чаем. 
Поблагодарил и поехал дальше на юг.

Проехал речки Орочо, Юркен, Горбылях. 
На отметке 810 км асфальт закончился. 
Дождь льёт, грунт тяжёлый, дорога ремонтируется. 

Остановился в посёлке Иенгра. 
Старая Золотинка или совхоз «Золотинка». Живут тут эвены, которые занимаются оленеводством и охотоводством.

А как всё было? Ехал по трассе и тут три эвена останавливают меня. Было это в 19.45, смеркалось. Я сначала подумал: не произойдёт ли всё как в Чурапче у якутов. Но нет. Всё наоборот.

Сначала познакомились. 
Потом предложили помочь: покормить и найти ночлег. 
Кто меня остановил был Гера, а другие двое братья: Егор и Миша Васильевы. Отправились в посёлок, к Гере домой. 
Расположился. 
Поскольку я с дороги, --- надо помыться. 
Пошли все мыться в баню. 
На самом деле мы пошли в котельную, где была горячая вода. 
Мылись парами в кабинках. Друг другу намыливали спину, а смывали самостоятельно. Я намыливал спину Егору. И что я увидел: у него вся спина была исцарапана и голова тоже. Но спрашивать не стал, мало ли что.

Затем был ужин. Чакушкой угостили. 
Завтра они уходят в тайгу.

Они оленеводы-охотники. 

> *Край красивый и обширный по территории. Люди очень доброжелательные и в тяжёлое время, в трудную минуту готовы прийти на помощь к любому, кто пришёл к ним с миром. Они желают мира другим народам и людям. Солнце одно и светит всем! «Сухун-Сиун»*.

Остановился у брата Германа, Игоря.

> *Егор поделился своими трагическими воспоминаниями, которые произошли в его судьбе. 
Он повстречался с медведицей и двумя медвежатами, когда он спустился с кедровика. 
Стрельнул и ранил её. 
Она располосовала ему череп: задела глаз, нос и по телу прошлась. 
Второй раз она атаковала его, уже когда он стоял за тонкой берёзой. Не успел он стрельнуть, как она ударила его по голове и он покатился вниз. Потерял сознание. Затем она его зарыла и ушла. 
Через полчаса он очнулся и пошёл. Нашёл карабин и пришёл опять к тому месту, где была медведица с медвежонком. 
Она стала прыгать на месте, рычать, а он затёкший кровью и с одним глазом шёл на неё с карабином. 
Она прыгала из-за того, что Егор проходил мимо кедровика, на котором был второй медвежонок. 
Когда он спустился медведица попрыгала с медвежатами и ушла. 
Егор не стрелял в неё. 
Он пошёл в посёлок, а до него 8 км. 
За 30 метров от дома он упал. 
Племянник Миша увидел его и отвезли в больницу. 
Крови много потерял. Но выжил. 
Вот такую историю рассказал Егор и его друзья. 
Теперь я понял, когда кто-то заходил в комнату сначала подходили к Егору и жали ему руку, а потом только ко мне, как гостю.* 

В свою очередь я тоже рассказал о своих приключениях, как у меня ломается багажник, рвуться спицы. 

> *Выслушав меня, они вручили мне 500 рублей и сказали, что это мне не на продукты, а на спицы. Чтобы я доехал до Москвы и рассказал о эвенах. 
Просьба охотников-оленеводов такова, что их ущемляют в правах, не дают охотничий инвентарь, снабжение патронами плохое и большие проблемы с местными кадрами.* 

В журнале моём выразили свои пожелания и просьбы. 
«Вспоминай нас - кто в тайге работает» и расписались:
Миша Васильев
Егор Васильев 
Герман Пудов
Игорь Пудов
Володя Константинов

***За день --- 80 км. Ок. --- 2562 км***

## 18.09.1992 г. пятница {#BAM-18-09-1992}

Встал в 7.30. 
Попил чай со сгущёнкой. 
Собрался, а Алексеев Герман дописал в моём журнале ещё одно обращение («Чуржени» называется) от имени малых народов посёлка Иенгра. 
Те, кто повстречается на моём пути - всячески помочь. 

В 9.10, поблагодарив, я продолжил свой прерванный вчера маршрут. 
К обеду я доехал до посёлка Нагорный, где протекает ручей Тимптом. 
В магазине купил молочную смесь за 40 рублей, груши --- 54 рубля. 
Было прохладно и я решил заехать в котельную, которая была рядом.

В 14.00 продолжил свой путь. 
Проехал ручей Холодникан. 
Дождь заморосил. 
Здесь водораздел. 
Преодолел перевал, поупираться пришлось. 

> *Открылся неплохой вид на окружающую местность. 
Стоят большие металлические коновязы. 
Внизу тоннель, состав, гружёный углём тянут четыре тепловоза. 
На этом месте кто-то и что-то должен оставить или повязать на ветку дерева. 
Вот и я привязал на лиственницу часть багажника и колечко от брелка. 
Здесь оказывается граничат Якутская АССР с Амурской областью. 
Этот монумент «СЭРГЭ» - дружбы и гостеприимства установлен 2 ноября 1976 года.* 

Ветер пронизывает, мёрзнуть начинаю. 
Пошёл на спуск. 

Внизу тепло. Солнышко пригревает. Совершенно другой климат. 
Станция Лапри и одноимённая речка протекает. 
Так тихо, уютно, просто юг какой-то! 

Проехал ещё 19 км и я пошёл в затяжной подъём на километра три. 
Вот почему в этой котловине так тепло. Она защищена от холодных ветров. 
Взял этот перевальчик и весь взмок, а ведь за ним опять спуск и не маленький. 
Опять продрог, но дорога выровнилась, справа ручей журчит, солнце светит, настроение бодрое. 
Припустил, чтобы согреться. 
Очень проголодался. 

Поворот налево и вижу указатель --- 4 км до станции Могот. 
Повернул и доехал до вокзала. 
Сразу бросается в глаза надпись на табло: «Горький - БАМУ». 
Там у дежурной поинтересовался, где можно остановиться. 
Она направила меня в депо. 
Там я встретился с рабочими депо, которые меня устроили в бытовке. Выдали мне кастрюлю и плитку электрическую.  
Поблагодарил их за такое внимание и принялся за работу.
Я сварил суп, поел. 
После занялся стиркой, починил велосипед, смазал цепь и заполнил свой журнал. 
Но у меня в журнале отпечатались только фамилии доброжелателей с их сокращенными должностями: Гнасенко --- опер., Абурахимова --- о/в, Гавришицын --- дер., Гикаченко --- ДСП.

***За день проехал --- 95 км. Ок. --- 2570 км***

## 19.09.1992 г. суббота {#BAM-19-09-1992}

Встал в 7.30, подогрел суп, попил чаю, прибрался и сдал помещение. 
Выехал в 9.15.

В 11.50 обед. 
Рядом табло: до Невера -190 км, а до Якутска уже 967 км. 
Солнечно и тепло. По небу бегут кучевые облака. Чувствуется дыхание юга. Скоро Тында! Там решим как дальше ехать или на Невер или направо по БАМу.

Посёлок Сигикта. 
Справа вертолёт, а вот и аэропорт.

13.30 еду уже по городу. 
На подъёме еду медленно, навстречу мужики идут. Спрашивают: «Сколько грибов насобирал?»

Еду и в магазины захожу. 
Ищу, где бы сварку найти, багажник починить. 
Нет, ничего не выйдет --- выходной. 
В спортмагазинах для меня ничего нет. Это очень плохо. 
Больших городов больше не будет, и долго. Столовок нет. 

На улице встретился с мужчиной, разговорились, познакомились. 
Его зовут Василий Михайлович Моисеев. 
Пригласил он меня к себе на чай. 
Познакомил с женой Татьяной, которая накормила вкусным обедом. 
Принял горячую ванну. 
После чего я сходил в магазин за продуктами, так как намеревался сегодня продолжить свой путь.

Вернулся и стал собираться в дорогу. 

> *Василий Михайлович подошёл и спросил, как я дальше собираюсь ехать. 
До Невера или поверну на Северобайкальск? 
А я в ответ у него поинтересовался - а как лучше? 
Он пригласил меня к столу, принёс карту и завязался у нас с ним интересный разговор. 
Первый вариант - спуститься до Невера и дальше по транссибирской магистрали. 
Но есть дорога по-труднее, но интереснее и увлекательнее. 
И посоветовал поехать по второму варианту, если не боюсь трудностей.* 

Я выбрал второй вариант. 

> *Василий Михайлович скоро уедет в Крым, а работал главным инженером на предприятии «Фундамент», директором которого был Кергизов Борис Александрович. 
Про строительство любых дорог всё знает. 
Он занимался строительством нагибальных зданий и сооружений, а также устойчивостью их, выдаче рекомендаций по любой этажности в условии слабых грунтов, в том числе и вечной мерлоты. Можем, сказал он, как прорабы выполнить фронт работ, кроме рабочей силы, по испытанию фундаментов и свай на предмет устойчивости их на грунте. Много интересных и трагических случаев было на Баме из-за  незнаний специфики строительства дорог и зданий в условиях вечной мерзлоты.*

Быстро стемнело и меня уже никто не отпустил. 
В тесноте да не в обиде. 
Устроился на полу и спал, как на сеновале.

***За день --- 70 км. Ок. --- 2727 км***