# Дорога на Транссиб {#transsib}

## 6.10.1992 г. вторник

Встал рано в 6.00. 
Собрался, попил чаю, поблагодарил Виктора и в 7.00 выехал. 
Ночью подморозило. Поехал по отсыпке вдоль железной дороги. 

Ветер встречный, небо ясное, солнце светит, но не греет. Холодно очень.
Дачные домики проехал. Снег на грунте, не растаял. 
Поднимаюсь на перевал постепенно.

Разъезд Тыя, заехал и поставил печать себе. 
Недалеко у дорожников привал сделал: покушал тушёнки с кабачковой икрой, запил чаем и вновь на штурм перевала пошёл. 
Солнце работать стало и мне теплее. 
С дороги свернул на отсыпку, которая идёт параллельно железке, по ней иногда лучше ехать, а бывает и короче. 
Это второй встречный путь, который когда нибудь будет тоже железнодорожный.

Слева показался посёлок Солнечный, где есть сероводородные воды, но я еду прямо. Спешу.

Солнце «поработало» и дорога от растаявшего снега стала мягкой. Очень трудно подниматься вверх. Но, чем выше поднимаешься, тем холоднее становится. Появился снежок.

Добрался до разъезда Гоуджекит. 
Зашёл, чаю попил,  отогрелся, попросил поставить печать. 
Про это место тоже печально говорят, называя как «долина смерти». 
Место не из приятных: ветер дует, вокруг камень, редкий стланик растёт и уже на сопках снежок лежит. Не курорт.

Пробовал сесть и поехать, не могу. Пошёл на перевал пешком. 
Догнал меня уазик. За рулём водитель, звать Александром, а напарник Виктор. 
Поинтересовались: «Куда еду?» 
После моего ответа, посоветовали мне заехать на метеостанцию, которая на перевале слева расположена. 
Сами они едут с войсковой части по охране тоннеля, до которого 1.5 км. 

Всё, перевал Дабан взят! 
Сворачиваю и подхожу к метеостанции. 
При входе, над дверью прибит герб Советского Союза! 
На самом деле это и снеголавинная станция в том числе.

Ребята хорошо встретили. 
Сразу за стол, знакомство - обед. 
> **tip**
После обеда вышел осмотреть окрестности перевала. 
Увидел в сторонке баньку и вернулся. 
Спросил на счёт баньки, рабочая? Ответили - да, но надо вычистить и вымыть. 
Я на радостях побежал к бане пока совсем не стемнело. 
Но работы действительно много. Надо вычерпать всю воду, а она вся ржавая, давно не топили и не слили воду. Быстро начал выкачивать воду и смывать ржавчину. 
В бане света нет. На ощупь приходилось работать. 
В 50 метрах был мелкий ручей, пришлось и тут попорхаться. 
Заполнил, затопил и только через три часа пошёл в баню. 
Пока топилась банька я заменил четыре спицы, зашил штаны и куртку. 
Поужинали в месте - уха из омуля была.  
Поинтересовался у ребят, какая дорога меня дальше ждёт? 
Конечно, рассказали и пояснили, а в журнале написали: «Сергей прошёл Даван, значит пройдёшь всё остальное». Суханов Виктор, Гувашов Александр.
Пар, конечно, был, но быстро уходил: видно щели где-то были. 
После каждого захода я бегал на ручей и окунался в холодный источник. 
Светила луна, были ярчайшие звёзды, морозец. 
Есть, что вспомнить! 

Это шестая моя банька. 
Четыре захода хватило мне, после чего я постирался и прогрелся хорошо. 
Промыл рану на надкостнице, заживает.
> **info**
За день 55 км. Ок - 3994 км

## 7.10.1992 г. среда

Встал в 7.00 и сразу в баню за бельём. 
Нательное бельё ещё сырое, не высохло. Видно быстро остыла банька. 
На себя одел. Высушу сам своим телом. 
Туман, маленький снежок припорошил перевал, морозец, на термометре три градуса мороза.

Перекусил. 
Одну спицу завязал у входа над дверью на память. Поблагодарил ребят и пошёл к дороге. На трассе сел и поехал. 
> **tip**
Проехал 500 метров со спуска и вижу два камаза стоят. 
Водители с нетерпением спрашивают: «Когда на перевал заедем?» Устали, замучились. 
«Полкилометра осталось»,- ответил я. 
С Набережных Челнов едут, перегоняют технику. 

Я же поехал со спуска осторожно: серпантин и очень круто. 
Внизу разъезд Дельбичинда. 
На метеостанцию зашёл. 
Там дежурил Юрий, который предложил отогреться и отведать горячего супчика. Ну как тут откажешься? 
В добавок печать на память от Юры. 
Попил чаю, поблагодарил и снова в путь. 

Еду. 
Стало теплее, ветер в спину! Веселее ехать, но снег лежит ещё.

12.15 заехал на станцию Кунерма, которую строил Дагестан. 
Зашёл, попил чайку, спросил про дорожную обстановку, отметился и с новыми силами поехал до разъезда с милым названием Умбелла.

К 16.30 был на месте, где пообедал, отведав тушёночки с хлебом и попил чайку с изюмом.

Проехал ещё один разъезд с весёлым и ласковым названием Окунайка. 
Темнеет, а надо доехать до станции Улькан. 
> **tip**
Темень, еду, а под колёсами, что-то хрустит и лопает, а иногда, кажется, что еду по стеклу и лампочкам. 
Жду когда зашипит камера после прокола или разрежу покрышку. 
Но всё благополучно кончилось. 

Появились огоньки над лесом, значит станция скоро будет. 
Стало радостно на душе. 
На другую сторону не перейти - пути заняты составами. 
Ещё один день подходит к завершению. 
Если даже проколюсь, то дойду, буду в тепле, отремонтируюсь, выйду из этого положения.

На часах 20.00. 
Доехал до вокзала. 
У кассира узнал, что за ТОЦ есть гостиница для МПС (Министерства путей сообщения), 160 рублей номер!
> **tip**
Зашёл, поздоровался, устроился. 
После начал знакомиться. 
Кого только здесь не было? 
Курбан Назарович директор Шахрисабского сахарного завода с Узбекистана. 
Монтажники Победа и Канат с Петропавловска-Казахстанского. 
Пожарный Семён Ахметов с Улькана. 
Затем пришла администратор гостиницы Люба с Наташей. 
Да я - с Эстонии. 
Полный интернационал! 
Кто сказал, что его нет? 
Дружба народов СССР налицо! 
Улькан строил Азербайджан. 
>
Поступило предложение поужинать. 
За такую встречу  пропустили все чакушечку. 
Завязалась задушевная беседа о наболевшем. 
Когда узнали, откуда и куда еду, то попросили поподробнее рассказать о своём путешествии. 
Начал свой рассказ и все с замиранием и очень внимательно слушали меня не перебивая, мне даже не по себе стало. 
Так заинтересовались и прониклись, что потом посыпались вопросы, советы. 
Предложения, например на обратном пути заехать к ним. 
Оставляли адреса свои или друзей, где я мог бы остановиться по пути следования. 
Всё это отражено  в бортовом журнале, который пошёл по кругу.
Семён нарисовал схему моего передвижения через реку Киренга. 
Так как мост охраняется военизированной охраной и прохода нет, а в объезд добрых 60 км, то он посодействует завтра и меня пропустят. 

Быстро пролетел вечер. 
После чаепития я осмотрел велосипед, смазал каретку, нарезал резьбу на педалях. 
Клин стёрся уже второй раз. 
Принял душ и в 23.40 уснул.
> **info**
За день 80 км. Ок - 4074 км

## 8.10.1992 г. четверг

7.00 встал. 
Приготовил кашу, чай. 
После завтрака поехал к Семёну в пожарку. 
Он связался по телефону с охраной моста на реке Киренга. 
Можно ехать.
К 10.00 мне надо подъехать и конвой будет ждать. 
Дал мне в дорогу сгущёнку, тушёнку. 

Подъезжая к вокзалу я попросил мальчика сфотографировать меня на фоне памятника Давиду - «Перекуём мечи на орала». 
С этого памятного и символичного места я выехал в сторону моста.
Пасмурно. До реки 18 км. Надо успеть. 

К 10.05 я подъехал к мосту через реку Киренга. 
Жду. Двое часовых с собакой двинулись в мою сторону с того берега. 
Открыли ворота. 
Переспросили и перевели меня на другой берег. 
Затем вывели на дорогу, показали направление и я поехал дальше до Магистрального.

В 13.00 я был уже в Магистральном. 
В столовой заехал и пообедал на 92 рубля. 
На почту: там нет связи. 
> **tip**
В администрацию посёлка заехал. 
Главы нет, поговорил с заместителем главы Беляевым О.П., который поставил мне печать в журнал. 
Узнал у него, что станцию строили Ставрополь и Ростов-на-Дону. 
Когда подъехал к администрации, там висел флаг РСФСР! 
Задал вопрос: «Что за флаг у вас висит?» Ответ был следующим: «19 августа 1992 года неизвестные лица сняли флаг и повесили старый. Так и висит по сей день» 
«Молодцы!», - ответил я и вышел. 

В магазине купил хлеб за 20.50 рублей, масло - 104 рубля.

В 14.00 покинул посёлок. 
Дорога сносная, ветерок встречный, чтобы скучно не было. 
Трудно идёт велосипед. 

17.00 туча на меня идёт. 
Думал дождь польёт, а тут снег повалил. 
Темнеет, на горизонте станция Небель показалась. 

В 18.50 подъехал к станции. 
Обратился к диспетчеру, звать Елена, которая была непротив и поставила печать в журнал. 
Рядом была кочегарка, в которой дежурил кочегар Александр. 
Переговорил с ним на счёт ночлега. 
Он был не против. 
Я расположился, принял душ. 
Поужинал. 
После составил маршрут на завтра, штопал, зашивал аммуницию.
> **tip**
Спросил Сашу: «Кто строил Небель?»
«А один сброд строил», - ответил он. 
Если в шутку сказал, то смешно, а если серьезно, то не смешно. 

БАМ строили мужественные и сильные духом люди. 
Это видно по железной дороге, которую преодолеваю каждый день.
> **tip**
За день 90 км. Ок - 4164 км

## 9.10.1992 г. пятница

6.00 подъём. 
Еле проглядывается солнышко среди туч. 
7.20 появилось солнце! Чай, сбор, в путь.
7.35 на трассе. Сухо. Хоршо ехать. Солнце очень радует душу. 
Через час снег пошел.

10.05 - избушка стоит. Я туда, перекусил. 
> **tip**
Проехал немного и увидел гранитную плиту на левой стороне дороги, рядом ручей бежит. Это памятник. 
Читаю: «ПИНХАСОВ ШАЛЬМИ МАНАХИМОВИЧ 
            1951-1976
        Мы дойдём до Амура
              ШУРИК 
             НИЯ-УЛЬКАН»
Вот это ответ Саше -кто строил БАМ! 
Я спрашивал бамовцев, что случилось с Шуриком? 
Вот такую я услышал. 
>
После смены, усталый он спал в вагончике, а в печке горел огонь.
Вероятно, вылетел уголёк... Вагончик сгорел. Несчастный случай. 

10.30 станция Ния, которую строили Россия и Грузия. 
Проехал не останавливаясь. 
Далее на отсыпку и до Звёздного. 
Снег не на шутку повалил. Землю уже всю покрыл. 
Тяжело велосипед пошёл. 

13.00 я в Звёздном. 
Бывшее название Таюра, очень красивое, таёжное, романтическое! 
Но после посещения космонавтом Леоновым этой станции назвали по-космически. Станцию строила Армения. 
Зашёл в пожарное депо, спросил как доехать до Усть-Кута. 
Пояснили и поставили печать на память.

Далее проехал по посёлку. 
Заехал в столовую, пообедал на 127 рублей. 
Хлеба нет в магазине, пришлось купить в столовой 5 кусочков. 
Чай залил во флягу. 
> **tip**
В столовой подошёл ко мне парень. 
Он пожелал мне всего хорошего, знает меня по рассказам своей жены Лены, которая дежурила в Небеле.
Что ж и вам всего доброго.

14.10 в путь. 
Тяжело. 
По отсыпке проехал 13 км и пешком по гравию вверх!! 
Ветер, снег, устал сильно. 
Дошёл до разъезда Чудничный. 
Зашёл. Дежурил тёзка Сергей. 
Попил у него чаю, перевёл дух. 
Он мне подсказал, как лучше проехать до Усть-Кута. 
Так и поехал, но темнеет, а я на спуск пошёл. 37 км ещё! 
То снег, то гололёд. У меня страх после падения и шишка на надкостнице чувствительная. 
Шлёпнулся два раза и ноги задрожжали. 
Снег валит. 
Осторожно! Синяки обеспечены. 27 км проехал. 
Уже город виден со спуска. Огоньки на той стороне Лены. 
Цивилизация рядом. 
Вот и разъезд Предленский. 
Остановился. 
20.00 на часах. 
Здесь и снега нет. 
> **tip**
На дежурстве была Елена Сартанова, которая должна сдать смену.  
Увидев меня и после того, как я представился, она сказала, что читала про меня в «Комсомолке» или в «Труде». 

Вот и сменщик пришёл, по фамилии Шолохов. 
В 21.00 ужин. 
Чай с колбасным фаршем.
> **info**
За день 130 км. Ок - 4294 км

## 10.10.1992 г. суббота

В 6.00 подъём. Сбор. 

Позавтракал и в 7.45 выехал.
Сухо. Маленький морозец. 
Проехал 8км и вышел к реке Лена. 
> **tip**
Нашёл хороший выход к реке, быстро разделся и искупался в великой реке! Хорошо! 
Поехал и активно кручу педали. 
Забыл перчатки. Пришлось вернуться, но не нашёл. Всё перерыл. 
Нашёл! С собой были. 

По реке прошёл колёсник «Красноярск» в последнюю навигацию в этом году. 
Красиво поплыл по течению, рассекая речку великую! На Якутск? 

Доехал до моста и пошёл пешком. Смотрю, как течёт Лена. 
Остановил мужчину, попросил сфотографировать меня на фоне реки. 
Он с Магадана! Это уже третий, кто с Магадана на моём пути. 
Ещё в конце моста попросил мальчика сфотографировать меня. 
Он оказывается в фотокружке занимается. 

На почту. 
Перед почтой №1 индекс (665780) транспорант с такой надписью: «Мы созидаем и в космосе мир утверждаем»
Саше Богданову телеграмму (13 рублей) о моём нахождении.

Теперь в столовую (86рублей). 
В магазин: яблоки, печенье, вафли. 
По пути увидел автобазу. Заехал и набрал запчастей для велосипеда.

13.20 выехал с города и поехал вдоль речки Куты.

15.00 привал на берегу речки. Подкачал заднее  колесо, что то спускать стало. Заменил нипелёк. Всё равно спускает. Заменил камеру и поехал, как ни в чём не бывало. 
Миновал ручей Островной. 
Ещё проехал 22 км. 

Станция Ручей, пожалуй здесь останусь на ночлег. 
Закат красивый, чистый, значит морозец будет ночью. 
Заехал на станцию, у дежурной спросил, где переночевать можно? 
Направили в гостиницу лесхоза, которая была совсем рядом.

Зашёл в гостиницу. Закрыта. Стучусь. Вышел мужчина, у которого спросил, можно ли здесь переночевать? Ответил, что нужно ждать дежурную, а мы тут прикомандированные. 
Их трое, места есть. Жду. 
> **tip**
Потом говорю: «Можно чайку у вас попить?» Они удивлённо: «Чаю? А у нас его нет.»
Я говорю: «У меня есть.» 
«Тогда оставайся», - чуть ли не хором говорят.

Выделили мне одну комнату. Я стал устраиваться. 
> **tip**
Им не терпится, стучатся, чай просят. Дал им заварки, а они меня просят, чтоб я свою тоже не выбрасывал. 
Оказывается у них чая нет, в стране с чаем напряжёнка. 
Потом они этот чай высушат и папиросок наделают.

Суп себе приготовил, соседи картошечкой меня угостили, хлеб и лук у меня всегда с собой был. Хороший супец получился, после которого потянуло на сон. 
Дежурная так и не пришла, видно на выходные ушла, а за себя прикомандированных оставила, которые закрылись и были на правах хозяев. 
Меня всё устроило: была крыша, койка, кухня, что ещё нужно? 
Мешать не буду, мне только до утра переконтаваться.
> **imfo**
За день 75 км. Ок - 4369 км

## 11.10.1992 г. воскресенье

Встал в 6.40. 
Доел суп, попил чаю, заварку ребятам оставил. 
Поблагодарил за гостеприимство. 

В 7.35 уже крутил педали. Сухо, морозец прихватил землю, и лужицы покрылись льдом. 
Солнышко поднимается. 
Пошли горочки, тягуны хорошие по три, четыре километра, которые  пришлось преодолевать пешком. 
Скоростей у меня нет, звёздочка-то одна.

Сибирь! Деревянные срубы пошли. Дикая природа. 
Проехал ручей Шалашный, посёлок Мерзлотка, а мне жарко. 
Подъёмы приморили. 

Первый обед в 10.30. - яблочки, хлеб с маслом и чай.

Через некоторое время на стоянке машину увидел. 
Поровнялся с ней. 
Ребята останавливают и к себе на на обед зовут. 
Свернул. Познакомились. Угощают: чакушку «сибайской», а она 50 градусов! 
Качан капусты в дорогу дали. 
Поблагодарил и в путь. 

Проехал 30 км и въехал в Хребтовую, которая встретила меня траурной процессией. 
Кого-то хоронили и я слез с велосипеда. 
Прошёл пешком, а  потом вновь сел на велосипед. 
В посёлке заехал в магазин. 
Хлеба нет, купил полкило сыра за 109 рублей. 

Наконец-то пост ГАИ. 
До этого, кажется, не было с Магадана! 
У постового Рината поинтересовался какая дорога меня ждёт и где можно остановиться. 
Он сделал набросок в журнале и посоветовал переночевать в Железногорске-Ильинском, который расположен в 13 км от трассы.

Доехал до указателя на Железногорск и проехал эти 13 км. 
Нашёл РОВД, где дежурный капитан милиции направил меня в ИВС (изолятор временного содержания лиц, находящихся под стражей), предварительно позвонив туда и дав распоряжение по мне. 
Поблагодарив Василия я отправился в ИВС. 
Там тепло встретили меня, предложили принять душ. 
Прикреплённый ко мне милиционер Игорь проводил меня и всё показал. 
После принятия душа, меня отослали в медвытрезвитель, где я и остановился. 
По пути я заехал в магазин и купил чай, хлеб, полкило масла. 

В медвытрезвителе дежурный Александр показал мне место ночлега. 
После чего я расположился и занялся своими делами: зашивал куртку, смазал цепь, сделал записи и наметил маршрут на завтра. 

После ужина, заготовил чай на завтра и приготовился ко сну. 
22.30 сон.
> **tip**
Часто на дороге можно увидеть знак: «Сужение дороги», но сколько можно сужать? А расширения нет. Ведь не проехать тогда. 

Это про мысли на полях.
> **info**
За день 95 км. Ок - 4464 км

## 12.10.1992 г. понедельник

Встал в 7.00. 
Собрался, поблагодарил ребят и в 7.45 выехал. 
Сухое шоссе, солнышко проглядывается. 
> **info**
Забыл фотоаппарат, а проехал уже 4 км. 
Рядом проезжал медицинское учереждение. 
Забежал туда, нашёл заместителя врача, Николая Фёдоровича Колотенко. 
Объяснил ситуацию. 
Он разрешил воспользоваться телефоном. 
После звонка в медвытрезвитель узнал, что дежурный Александр ещё не сменился и нашёл мой фотоаппарат. 
Николай Фёдорович предоставил мне машину «ниву» с водителем, которого звали Юрой. 
Поблагодарив его, я быстро съездил с Юрой за забытым фотоаппаратом, сел на велосипед и покатил дальше.

Доехал до поста ГАИ, где вчера дежурил Ринат. 
А сейчас наряд в составе трёх человек: инспекторов дорожной службы Юрия и Николая, а также водителя Алексея пригласили меня на чай.
Угостили домашними оладушками, а Алёша копчёными колбасками. 
Поблагодарив коллег я в 10.30 продолжил свой вояж.

Проехал 46 км по хорошему шоссе до речки с интересным названием Иреек. 
Свернул пообедать. Живописное место нашёл на опушке, рядом с речкой.
> **tip**
Проезжал автобус «ПАЗ», который тоже свернул и остановился. 
Ко мне подошёл один из мужчин и предложил подойти к автобусу и помянуть родственника. 
Я подошёл, сел у гроба, мне налили 50 грамм и дали закусить. 
Мужчина вёз своего дядю хоронить.

15.45 поехал дальше. 
Асфальт закончился и пошёл гравий, но хорошо укатанный и можно ехать.

Проехал реку Илим, красивая и полноводная река. Дачные домики стоят, самого посёлка нет.

17.30 лёгкий ужин, чай с вафлями. 
Доехал до дорожников, у которых тоже попил чаю. 
Проехав их пошёл вновь асфальт. 

Вот и день заканчивается, темнеет. 
В 19.05 въехал в посёлок Видим. Ярко светит луна. 
Еду по центральной улице. 
Ищу, где бы остановиться. 
Прямо у дороги, справа, стоит пожарная часть. 
Свернул, зашёл в дежурную часть. Обратился к начальнику караула, объяснил ситуацию, после чего получил добро. 
Наряд меня сразу принял, показали койку и пригласили поужинать. 
> **tip**
Пожарные - обычно гостеприимные  ребята, готовые сделать для тебя всё, чтобы ты ни в чём не нуждался, конечно, что в их силах и возможностях. 

Пожарный по имени Михаил, хоть и не очень грамотно, но искренне пожелал удачно добраться до Таллина.
> **info**
За день 119 км. Ок - 4583 км

## 13.10.1992 г. вторник

Встал в 6.45. 
Попил чаю. 
Собрался, поблагодарил караул и выехал на трассу в 7.55.
Морозец. Встаёт солнышко и это радует. Хорошо ехать. 
Через 8 км пошли ручьи с названиями: Майдар, Мамырь. 

10.45 обед у речки Кежма: колбаска копчёная, хлеб, печенье, вафли, чай.

Привал у временного «шалаша». Тишина, редко машины пробегают. 
> **tip**
**Для памяти**: 
В 13.30 на 287-288 км от Усть-Кута на подъёме пришли мысли о пройденном и предстоящим пути: 
> 1. Колымский тракт - хорошо.
> 2. Хандыга-Якутск - тем более. 
> 3. Аямтранс - в придачу для утверждения.
> 4. БАМ - десерт.
> 5. Ленский тракт - закваска.
> 6. Трансиб - для закрепления пройденного пути.
> 7. Московский тракт - для полного удовлетворения.
> 8. Москва-Таллин - для полного счастья!

14.30 обед прямо на остановке.

16.30 приближаюсь к чему-то цивильному. 
Дома появились. 
Братская ГЭС! 
Проехал плотину. Громадьё. 
Самое узкое место Ангары перекрыли в 1966 году.

17.30 - проехав плотину, свернул к Братскому морю. 
Искупался! 
> **tip**
Как хорошо. 
И всё это «прекрасный МИГ, между прошлым и будущим, который называется ЖИЗНЬ!» 

Быстро оделся и на велосипед. 
Кручу педали, согреваюсь. 

По пути увидел почту, отделение №33 и сразу туда. 
Мне надо ребят известить, где я сейчас и что со мной. 
> **tip**
Как всегда связному по Магадану - Богданову Саше телеграфирую: «Искупался. Даёшь Ангару!» 
10 рублей за такое известие. 
Телеграфистка изумлена и спрашивает: «А где вы искупались, вам не холодно?» 
Отвечаю: «Напротив почты искупался, это в память о Братске!»

Недалеко был магазин, где купил хлеб уже за 30 рублей и пиво за 12 рублей.

На посту ГАИ поинтересовался, как лучше проехать Братск и выехать на дорогу, которая выведет меня на Тулун.
После полученной информации налёг на педали, так как город Братск очень разбросан и мне ещё ехать и ехать. 

Проехал около 30 км. 
Уже совсем стемнело, еду в слепую, не знаю куда. 
Крутые горки на моём пути. 
Стал искать место для ночлега. 
Никаких зацепок. Усталость приходит. 

Появился длинный высокий забор с такими же высокими воротами. 
На воротах есть вывеска с надписью. Прочитал - это водоканал. 
Всё закрыто. Звонков нет, а само здание в 50 метрах от забора. 
Ждал, может кто выйдет. Нет, надо что-то делать. 
Перелез - и в дежурку. Постучался. 
Открыла дежурная, звать Лена. 
Ей объяснил свою ситуацию, что совершаю велопробег и мне надо где-то переночевать до утра. 
Попросил: можно ли здесь остаться. 
Она разрешила и кроме этого накормила картофельным пюре, а у меня, кстати, была копчёная колбаса. 
Потом было обильное чаепитие (пять кружек осушил) и длинный рассказ о пройденном пути. 
Сегодня хорошо потрудился и усталость пришла. 
Сделал запись в журнале и в 23.35 уснул.
> **info**
За день 130 км. Ок - 4713 км

## 14.10.1992 г. среда

В 6.50 встал. 
Кашу приготовил. 
Чай во флягу заправил. 

8.00. Поблагодарил Лену за приём и поехал своей дорогой дальше.

Проехал 22 км и остановился у поста ГАИ (9.50). 
Подтянул спицы, две лопнули. Это от вчерашних горок разболтались колёса и спицы перетёрлись. 

Инспектора Володя и Сергей пригласили на пост и предложили перекусить. 
Выложили салат, колбасу. 
Всё запил чаем. Ребята же смотрели по ТВ сериал про Марианну, «Богатые плачут». 
Поблагодарил и в путь. 

До следующего поста 12 км, посёлок Вихоревка.

Доехал до очередного поста быстро. 
Там переспросил, как мне дальше ехать. 
Если ехать прямо до Тулуна, то дорога хорошая, шоссе, но длиннее почти на 250 км. 
А если свернуть сразу на Тайшет, то короче, но дорога вдоль железнодорожного пути и не везде есть шоссе. 
Мне не привыкать, выбрал короткий путь. Дорога посложнее, потерплю. 
Да мне и спешить надо.

Проехал пару километров и пошёл гравий. Дорога строится. 
Ветер встречный добавился. 
Горки в добавок. 

Доехал до городка дорожников. 
Обед у них. 
Доброжелатель Николай презентовал дорожную куртку от дождя. 
Он же посоветовал помыться в бане. 
Пошёл, но банщик не пустил, так как я может быть больной!? 
Заведующий гаража тоже не дал помыться. 
Видно у них кто-то, действительно, больной был. Обожглись! Теперь на воду дуют.

К дорожникам привезли хлеб на «Ниве». 
Водитель Николай, он и мне один кирпичик дал. 
Поблагодарил и в 16.00 отправился далее по грунтовой дороге в сторону Тайшета.
> **tip**
По пути попалась свалка и там увидел велосипедное колесо. Остановился и поскручивал шесть спиц.

Солнце закатывалось, проехал 37 км. 
Далее к станции Огнёвка пробирался пешком по просёлочной дорожке.
На ней-то и встретил сначала мальчика Витю, а затем его отца Александра и мать Ирину. 
Разговорились, дошли до их дома. 
Спросил, где можно здесь переночевать до утра. 
Они тут же предложили остаться у них. 
Гостеприимными оказались мои случайнае встречные.

Накормили супом из зайчатины. 
Виктор на петлю поймал. 
Деревенька, с красивым названием Огнёвка, стоит на высоком холме, да на солнечной стороне и откуда открывается красивый вид на тайгу. 
Внизу проходит железная дорога.
> **tip**
После ужина смотрели телевизор. 
Показывали Таллин, замок Тоомпеа (Совет Министров), который когда-то охранял мой взвод, я был там взводным.
>
Семья видно дружная. 
Ирина Васильевна Малинина (Елькина) немного рассказала про себя.
Живут они втроём: муж, Александр Александрович и сын Виктор. 
Она была тоже в Магадане, завербовалась в 1957 году, кода ей было 19 лет. 
Она с 1938 года рождения, родом с Перми. 
Сын не учился, есть отклонения. 
Зайцев ловит, помогает дома по хозяйству. 
Ухаживал за ней милиционер, у которого болела жена. 
Она за женой ухаживала, пока та не умерла в 25 лет. 
Перед смертью дала добро на то, чтобы после того, как уйдёт из жизни, они были вместе. 
Но расcчиталась и тихонько уехала.  

> **info**
За день 73 км. Ок - 4786 км

## 15.10.1992 г. четверг

В 6.30 подъём. 
На завтрак бульон из зайчатины, чай. 

Поблагодарил гостеприимную семью и отправился на станцию Огнёвка, где мне поставили ещё одну печать в журнал. 
Поинтересовался, какая меня ждёт дорога. 
До следующей станции Торея мне ехать 18 км по грунтовой дороге.

Туман стелется: погода обещает быть солнечной и это радует.
> **tip**
Сельская дорога, похожая на ту, где мать родилась. 
Это как ехать с Плёса до Усолья. 
Виляет, ямы и колея заполнены водой. 
Ход тяжёлый. 
>
На одном участке разогнался со спуска и на повороте показалась большая лужа, стал объезжать, а там яма! Вот и нырнул головой в землю, хорошо шапочка была на голове. 
Грязи немерено, видно недавно дождь прошёл и машины дорогу намяли. Забившуюся грязь постоянно приходилось с велосипеда смывать.

Большой подъём, длинною в 2.5 км преодолел, нашёл приятное место и перекусил. 
Немного проехав, увидел станцию Торея. 
У местного жителя спросил, где почта. 
> **tip**
В 12.00 закрывается на обед. 
Бланк у меня был. 
Переговорил с приёмщицей. 
Она поняла: взвесила поклажу, дождалась. пока я заполнил бланк, подписал коробку, а после вручения ей посылки сказала, что завтра же отправит её.
Закрыла почту и пошла на обед, а я облегчённо вздохнул. 
Мне станет легче ехать, а отцу она нужнее сейчас будет. 

Тут же хлебная лавка подошла. 
Всё одно к одному! Бывает и такое. 
Купил хлеба, который здесь стоит 21 рубль. 
Заменил спицу.

В 13.00 в путь на Кешево это 24 км. 
> **tip**
Дорога!!! Грязь, болотины. 
Где и на себе нёс велик. 
Однажды на коленях вынес велосипед из ямы. 
Вот помучиться пришлось. 

Проехал Кешево и дорога лучше пошла. 
Дорога глинистая, но сухая. 
Здесь дождь стороной прошёл.

18.00. Подъехал к разъезду №14 станции Чукша - не рабочий. 
До Тайшета 178 км.

Недалеко скотний двор, а рядом домик, где разговаривали женщины. 
Подъехал к ним и спросил, где здесь можно переночевать? 
Пошли спрашивать у хозяина. 
Вернувшись, дали - добро. 
Подъехал сын хозяина Сергей. 
Он запустил к себе в дом и предложил располагаться. 
Я принёс воды с колодца. 
Хозяйка дала картошки и луку. 
После чего я стал варить суп.
Вскоре и хозяин появился.
> **tip**
Он с порога: «Сразу видно - наш человек!» 
Познакомились, его звать Анатолий, с 1928 года рождения, как и мой отец. Только Анатолий на два дня моложе - 28 февраля. 
К чаю варенья стакан принёс.
После ужина помылся, постирался и принялся за починку велосипеда. 
Чтобы не было скучно Сергей магнитофон включил. 
>
В лесу и в деревне изобилие лосиных клещей. 
Ползают по всему телу: залезают в волосы, в штаны. 
Неприятные ощущения. 
Перед сном вышел на двор, светила уже «стареющая» луна. 

Тяжёлый день был. 
> **info**
За день только 62 км. Ок - 4848 км

## 16.10.1992 г. пятница

7.30 встал. 
Приготовил кашу, попил чаю, собрался. 
Зашёл к Анатолию, поблагодарил его и попросил безхозную покрышку, которая висела во дворе. Сразу выпалил: «Бери!» Взял, скрутил и привязал к багажной сумке.

Перебрался через железнодорожные пути и далее по грунтовке поехал.
Еду, вижу стоит уазик, похоже угнанный. 

У дороги стоит геодезическая вышка. 
Подъехал и решил залезть. 
По ходу считал ступеньки, насчитал сорок одну. 
Обычно я их не пропускаю и стараюсь забраться. 
Оттуда открывается прекрасный вид на близлежащие окрестности. 
Видно куда дорога ведёт. 
Делаю фото и получается вид с птичьего полёта.

Жарко стало. 
Доехал до Чуны. 
Зашёл в РОВД, дежуривший старший лейтенант Сергей Ковальчук поставил печать на память в журнал и подсказал, как проехать до столовой. 

Отобедал на 69 рублей. 

В путь. Жара. 
Еду по гравийке, ветер усиливаться стал. 
> **tip**
Мысли лезут в голову:
                 Порой я себе уже не принадлежу.
                 Я кому то нужен, но не себе.
                 И что меня тянет вперёд!

В 17.00 остановился у чистого ручья, охладился, простирнул нижнее бельё и тут же одел. Сохнет на мне быстро. 

Проехал ручей Джигикан. 
Заволокло небо свинцовыми тучами. 
Ночлег надо искать. 
Остановился у фанерной будки, которую ставят на грузовую машину, людей перевозить. Сильно помятая, видно авария была, но для меня она сгодится. 
На встречу ехала военная машина.
> **tip**
Остановил и спросил: «Далеко ли населённого пункта?»
Ответили: «Примерно 50 км.» 
Да, далеко, видно это до Квитка.
Офицер был за старшего и выделил мне 3 литра воды, хлеба, банку шпрот, банку кеты, банку каши. 
Поблагодарил и они уехали.

Я перевёл через насыпь велосипед и там раположился, чтобы меня не было видно с дороги. 
> **tip**
Сначала хотел развести костёр, сварить кашу, чай. 
Но передумал. 
Место глухое и безлюдное. 
Машины проезжают очень редко. 
Привлекать к себе не стоит. 
Осмотрел будку и стал благоустраивать её под ночлег. 
Внутри сделал шалаш из сосновых веток. 
Осмотрелся: меня с дороги не видно. 
Замаскировал велосипед, чтобы не отсвечивал от проезжающих машин.

Поужинал, запил холодным чаем. 
> **tip**
Включил радио, слушаю новости. 
Передают, что Е.Гайдар посетил Магадан. 
Говорит, что такой большой город не нужен и надо сделать его вахтовым. 
А подумал - хорошо? 155 тысяч человек в городе! Как и куда перевозить людей? 

Забрался в корейский спальник и пытался уснуть.
Ночью ветер дул хорошо. Пять машин прошло.
> **info**
За день 97 км. Ок - 4945 км

## 17.10.1992 г. суббота

Встал в 5.00. 
> **tip**
Не спится. 
Приснился Саша Томашевский, друг, коллега с Магадана. 
Юра Лютер одноклассник, в легкоатлетической секции вместе занимались.

Похолодало. Оказывается выпал снег. 
Послушал новости. Поел кашу с хлебом и запил водой.

Собрался и в 6.20 поехал. Темно ещё. 
Лёгкий снежок падает. Ветер встречный, грунт тяжёлый.

После 20 км прошла первая машина. 
За 48 км до Тайшета проехал заброшенную деревню. 

А вот и Квиток. 
Увидел котельную и туда. 
Познакомился с кочегарами Михаилом и Рудольфом Кузнецовым. 
Попросил присмотреть за велосипедом, а сам в магазин за продуктами пошёл. 
Купил копчёной колбасы, масло, сгущёнку. 
Вернулся и перекусил. 
Напился чаю со сгущёнкой. 
> **tip**
Рудольф оружейник, в 1953 году его амнистировали. 
Сидел в Бодайбо за оружейные дела. 

Разморило. Прилёг и уснул. 
Кочегары прикрыли меня. 

В 15.15 встал. 
Попил чаю, поблагодарил за приют и отправился в путь. 
По пути купил печенье. 
Снег не прекращается. 

Спустился с горки и кончился асфальт. 
Вновь подъём солидный - 2.5 км. 
До вершины пешком добирался. 
Дорога от снега тяжёлая, хотя он прекратился. 

Переехал речку Байроновку, но, думаю, Байрон здесь не бывал. 
А вот деревня Гоголевка очень приятно выглядит. 
Пришвартовался к ближайшей остановке и попил чаю с печеньем.

18.00 на часах, до Ленского тракта 20 км примерно. Еду. 

До Тайшета 13 км! 
500 метров и шоссе пошло! 
Прощай гравийка! Когда ещё увидимся?
> **tip**
Идёт по шоссе охотник. 
Остановился, разговорились. 
Его звать Евгений. 
Попросил его сфотографировать меня с его ружьём. 
Он сначала ружьё дал и тут же взял обратно. 
Вытащил патрон и вернул мне. 
Сфотографировал. 
И мы, беседуя, пошли в сторону города. 
Охота открыта и у него есть трофеи: рябчик, глухарь и козочка. 
Я коротко рассказал о себе. 
>
Евгений зовёт меня к себе в общежитие на Узловой переночевать. 
Я согласился. 
Дал мне адрес, телефон. 
>
Живут они с женой Леной вместе, а дочь Евгения выше этажом. 
Сам он придёт попозже, надо ещё свои места пройти. 
>
Вдруг на нас утки летят. 
Он вскидывает ружьё, а патрон-то он вытащил! Потом сокрушались оба. 
Ничего пусть живут. 
После этого момента он отпустил меня. 

Я быстро нашёл общежитие и комнату. 
Открыла дверь Лена, жена Евгения. 
Всё рассказал, как мы познакомились с Евгением и что он придёт попозже. 

Лена накормила меня. 
После чего я помылся и постирался. 
Сделал записи, по ТВ показывали авторский вечер с Анне Вески в Останкино. 
Лена отвела меня в свободную комнату общих друзей. 

В 2.00 я уснул.

В 3.00 Евгений пришёл с охоты. 
Я сразу же встал. 
После был «танец живота». 
Ели печень и сердце косули. 
Слушали рассказы заядлого охотника до 4.00.

В 6.00 приехал Олег с Иркутска, владелец комнаты, где я разместился.
> **info**
За день 80 км. Ок - 5025 км

## 18.10.1992 г. воскресенье

В 9.00 подъём. 
Завтрак. 
Поблагодарил гостеприимную семью, собрался и отправился в дальнейший путь на запад.

В 9.55 был на трассе. 
В 10.35 выехал с города. 
Пересёк речку Озёрную. 
11.00 проезжаю мост через реку с прекрасным названием Бирюса, которая «поёт на все голоса». 
Она же - река Она. 
Сделал фото на память и в путь. 
Видно место, где когда то пришвартовывался паром. 
Мост построили видно не так давно. 

Проезжаю Юрты, Тополино-Черемхово. 

12.45 деревня Черемшанка, обед на лужайке. 
Прохладно, но солнце проглядывает.

14.20 граница Иркутской области с Красноярским краем, конкретно, -  Нижне-Ингашский район. 
Часовой пояс тоже другой, по местному 13.20. 
Четыре часа с Москвой разница и с Магаданом тоже четыре.

После селения Решёты пошёл асфальт, бетонка.

Вновь на пути геодезическая вышка. 
Забрался - 51 ступенька. 
Проехал и ещё одна - 65 ступенек.

Закончилась бетонка, опять гравий и незначимый объект - деревня Тины. 
Вышел вновь на отличное шоссе, солнце закатилось. 
Велосипед катит хорошо.

19.00 я въехал в Нижний Ингаш. 
Нашёл РОВД, там поставили печать и подсказали, как доехать до дома Саши Козадаева. 
Тут и родственник Саши на дежурстве был. 
Хотя Саша мне ещё в Магадане расписал, как доехать и набросил маленький план.

Вот и дом увидел, прямо на него держу курс, еду через поле. У дома за изгородью стоит мужчина. 
Спрашиваю: «Саша дома?» 
«Да», - услышал в ответ, а сам подумал: почему он здесь?

Мужчина открыл мне калитку, я заехал. 
«А где он?» - спросил я. 
«Скоро придёт, дома траур - у него отец умер, сегодня девятый день!», - последовал ответ. 
Меня как рубануло. 
Саша сказал, что отцу сообщил и он тебя встретит. Вот так встреча...

Я помылся и мы помянули. 
Вскоре и Саша пришёл. Обнялись, помянули. 

Саша сказал, что отец меня ждал и хотел пожурить за такой дерзновенный шаг. Не услышал я этих слов. 

Очень устал за день, очень вкусный ужин был. 
Меня быстро ко сну потянуло.
>
Мысли опять пришли: «Велопробег - это память о Колыме, о службе, о коллегах, о друзьях, о Севере!»

А памятью жив человек!
> **info**
За день 119 км. Ок - 5144 км