# Омск --- Казахстан {#Kazahstan} 

## 19.07.1993 г. понедельник {#Kazahstan-19-07-1993} 

В 6.00 подъём. Завтрак: два бутерброда с сыром, чай. Геннадий Александрович с сыном Евгением проводили меня до гаража, где перезимовала моя "перламутровая девяточка". Крепкое рукопожатие. 

"Спасибо и до новых встреч" --- с этими словами я отправился к тому месту, где в прошлом году, 11 ноября меня подобрали Николай и Слава.

Тогда, в метель и холод они, проехав меня, вернулись, на "газ-66" и погрузили велосипед вместе со мной, довезли до Омска. А подобрали они меня недалеко от деревни Мангазёрка, где я переночевал с 10 по 11 ноября.  

Выехал в 7.15 на набережную Иртыша, затем повернул на главную дорогу, которая отмечена на карте за №51. Ближайший ориентир населённый пункт --- Сыропятское. 

Появились километровые столбики: "885 км" --- это указатель в сторону Калачинска, на Восток, навстречу солнцу. Еду, солнце в лоб, печёт, жарко! На обочине много лужаек, заполненных чистой водой  от прошедшего недавно дождя. Искупался в одной из таких луж, освежился, отдохнул, а перекусив отправился дальше в путь.  

За 20 км до Нижней Омки, у пруда я сделал очередной привал. Искупался. Без воды никак. Солнце палит! Заправился в очередном населённом пункте водой, без которой просто невозможно ехать.

Циклон, видимо, прошёлся хороший, вода не успела вся пропитаться землёй и получился травянистый настой, который, я думаю, и очень полезен, когда в нем отмокаешь.

Поля чередуются берёзовыми рощами. Июль, сейчас для сельского жителя сама страда пошла: у кого сенокос, покосы, а кто-то уже сено ставит.

Дорога ровненькая, почти без подъёмов. Это Барабинская низменность. Проехал село Резановку, это последний населённый пункт в Омской области. Условная граница и я въехал в Новосибирскую область. Среди берёзок указатель стоит и показывает  142 км. В тенёчке сделал привал, перекусить. 

Подъехал старичок со старушкой на телеге. Приехали покосить траву. Остановились, распрягли лошадку. Я подскочил, помог жеребца подержать. После чего продолжил свой путь. 

Появился лёгкий, свежий ветерок, который приятно ласкал загорелое тело. Появился гравий. Руки от вибрации неметь стали и побаливать. Кровь не поступает от пережатого запястья, появились мозоли. Багажник сразу отреагировал на такую тряску. На заднем багажнике сварка отлетела.

Проехал Еланку, слева появилось поле с указателем, на котором было начертано: "Поле Геннадия Толстова".
   
Въехал в населённый пункт Усть-Тарка. По ходу завернул на охраняемую базу. Там нашёл станцию техобслуживания, где ремонтирую машины. Сторож помог мне связаться со сварщиком, которого звали Николай. Он быстро заварил мне багажник. На часах было 23.00. Поблагодарив его за оказанную помощь, я смог проехать ещё 15 км. 

Остановился у живописного места. Меня окружали маленькие дачные домики, рядом было озеро. Свернул с дороги и пошёл искать место для ночёвки. Выбрал постройку, обустроил место для ночлега, прикрыл дверью проход. Устроился поудобнее и сделал запись первого трудового дня. Много на дороге разной раздавленной живности. Сегодня, например, две совы встретились, несколько ворон. А под занавес дня встретил ёжика. Нагнал его, а он убегает. Когда поравнялись, он съёжился и ждёт... Их тоже много давят, хотя они думают, наверное, что у них иголки и это залог хорошей обороны. Но против автомашин это не играет. Сколько жаб и лягушек расплющенных! Всю живность жалко. 
   
В 23.45 укрылся и спать. Комаров!!! Укроешься от них, но становиться жарко спать. Не дали поспать, всю ночь ворочался.

***За день --- 201 км. Ок. --- 6996 км***

## 20.07.1993 г. вторник {#Kazahstan-20-07-1993} 

Встал в 6.00. Собрался и в 6.40 был на трассе. Проехал село Камышово. Всё ещё по гравию еду. Миновал Вознесенку. Солнце, опять жарко! Свернул и перекусил: печенье, вода с сахарным песком.  Ехала машина скорой помощи. Остановились, поинтересовались куда еду. Угостили хлебом, а я их благодарностью. 

Солнце палит нещадно. Силы уходят, да и вчера хорошо потрудился. Спать тянет. Заехал в приятную берёзовую рощу, лёг под берёзки и уснул на часок. Встал, легче стало, отошёл. Бодренько себя чувствую.
  
В 11.00 продолжил свой вояж. Въехал в большое селение Венгерово. Нашёл столовую и на 420 руб. хорошо поел. Выпотел и захотелось восполнить затраты, поэтому взял груздей, солёных огурчиков. 

Заехал в администрацию за печатью. Заместитель главы поставил печать, пожелал лёгкого пути. На вопрос, почему такое название? Ответил --- названо в честь партизана.

Ветерок обдувает. Через 20 км проехал Труновку. Вот и речка Кама, та, которую зимой в "газ-66" проехал двадцатиградусный мороз и метель. А сейчас лето, жара. Искупался, но вода грязная очень, илистая. Обсох и на своего коня. Я снова в пути.

Заехал в Покровку, в магазине купил томатного сока и закуску на 380 руб., а за деревней в лесу перекусил.

Вдалеке показалось Антошкино. Здесь опять печёт. На обочину и в луже отмокаю. Высох и в путь. Встречаю колонну "камазов". Остановили. Едут в Шипицыно через Венгерово. Звали с собой. Чакушкой угостили и отобедали вместе. В дорогу дали сало, лук, хлеб. Поблагодарил. Предлагали здесь остановиться у вдовушки и адрес давали, но мне ехать надо до Мангазёрки. 

В 22.00 был уже в Булатово. Набрал колодезной воды, разлил по флягам и дальше в путь. На 1158 км остановился, съел закуску, запил водою, а на километровый столбик накинул покрышку, на память! Это то место, где подобрали меня ребята в прошлом году. Зима была. Место плохо узнаваемо. Слева, в двухстах метрах, памятник стоит водителю.

Темнеет. Подъехал к Мангазёрке в 23.30. В конторе идёт для жителей деревни индийский фильм. Жду, когда фильм закончится. Подошёл к киномеханику, познакомились. Его звать Валентин. Живёт один. Жена Людмила врач --- ушла, живёт в Подмосковье с мужиком, как он говорит. Мать умерла, 1926 года рождения. Держит скотину: корову, двух телят, кур, овец. После, как управился, пошли к нему домой. Поужинали: окрошка, сметана, чай. В доме ещё две кошечки и две собаки. Да, не скучно! Дочь Оксана,ей 21 год, ушла в монастырь (в Псковско-Печорскую лавру). Валентин говорит, что дочь способная, поступила в институт и бросила. В "Гнесинку" поступала и не прошла... 

> *Это место мне знакомо, был там на школьных каникулах после 7 класса. Заехали мы тогда в город Печоры, Псковской области. С нами тогда была классный руководитель Светлана Фёдоровна Безобразова и мой первый тренер Ян Оскарович Пяллинг, у которого там жила мама. Он воспользовался моментом и навестил её, а я попросил его взять меня с собой. Вот такие навеяло воспоминания в далёкой Мангазёрке.*  

***За день --- 150 км. Ок. --- 7146 км***

## 21.07.1993 г. среда {#Kazahstan-21-07-1993}

В 5.40 подъём. Новости по радио прослушали. Сообщают, что ваучеры и ваучеризация страны --- это незаконно. Направили запрос в конституционный суд: проверить законность и приостановить ваучеризацию. 

Позавтракали: яичница, сметана, два стакана молока, чай. Жидкости стал пить больше. Жара сказывается. Поблагодарил Валентина за гостеприимство и в 7.15 выехал на трассу. Багажник развалилсЯ полностью. Подвязал его и в путь.

Доехал до Антоново. Рядом колонна ДРСУ, тут же и сварка есть. Ребята быстро заварили. Володе сварщику --- персональное спасибо. Фото на память. До Барабинска 13 км. Жара. Солнце нацелено прямо в глаз и темечко. В Барабинске купил пива за 120 руб., бутылку сдал. Работает! Напиток --- 12 руб. стакан.

Всё этот участок я зациклил. Теперь мне надо доехать до Пикетного, где 14 ноября 1992 года принял решение продолжить свой велопробег Магадан-Таллин уже в 1993 году. Купил на вокзале билет на поезд Тында-Москва №75, вагон №13, место на подсадку, до Омска, дали! 655 рублей.

Подсел к семье: Володя и Таня с детьми. Разговорились, такие внимательные и добросердечные люди живут в такое непростое перестроечное время! В Омск прибыл в 18.30. Володя помог мне спустить велосипед. Я поблагодарил и мы расстались. 

В 19.01 купил билет на Пикетное. Попросил юношу помочь мне сесть на поезд и сойти на станции Пикетное. В 20.30 я был на месте. Опять направился в пикет. И вот чудо: там дежурит Саша, у которого я коротал время 14 ноября 1992 года, в ожидании электрички на Омск! Я ему сразу: "Узнал? А ты что, с прошлого года всё дежуришь и не кому сменить?!" Засмеялись оба. Стали чаёвничать. Рассказал ему, как провёл время своего отсутствия. Есть что рассказать друг другу. Умылся перед сном на колонке.

## 22.07.1993 г. четверг {#Kazahstan-22-07-1993} 

В 6.00 встал. Чай, сбор. Поблагодарил Сашу и на выход. В 7.00 выехал с Пикетного и по совету Саши поехал по прямой на трассу. Туман стелется по земле, опять жарко будет. 

Выехал на трассу у километрового столба, 742 км до Челябинска.

Проехал 60 км, на часах 10.15. Неплохо еду. Пришло время перекусить и передохнуть. Перед привалом проехал указатель: "Спартак --- 6 км". На этом участке уже три ёжика стали жертвами машин.

В 10.50, после отдыха в путь на Исилькуль --- это граница с Казахстаном. 

Проехал немецкое селение Грунфунсталь, ещё 8 км и таможня. На границе печать таможни и я въехал на территорию Казахстана. Заехал в столовую и за 800 руб. отлично поел: три беляша с картошкой, три котлеты, пиво, сырок, лимонад, два лимонада разлил во фляги.

Затоварился и поехал. Вот ещё жертва --- ёжик раздавленный. Проехал около 100 км, сделал привал и обмыл ноги в дождевой луже. На остановке мужчина-инвалид шашлыки продавал. Дал воды попить. 

До Булавино 5 км. Проехал немного и опять в дождевую купель отмокать лёг. Как легко после этого ехать. Вода настоялась в траве, лекарственной стала, настой, бальзам.

Появилась туча, нагнать меня норовит. Припустил. Перегонять её стал! Затем она остановилась и на меня обрушился встречный ветер. Так от дождя ушёл. Ещё 22 км проехал --- село Фурманово, а за ним привал сделал. Ещё один ёжик придавленный на дороге лежал. Проехал 20 км и привал. Пить хочется. Вот такими отрезками и передвигаюсь. 

Перекрёсток, указатель  поворот на Токуши.  
21.00. Проехал немного, 3-5 км и на указателе стоят цифры: 34 км до Петропавловска (Казахстанского). Жарко. Воды больше нет.  Еду на зубах. Очень устал. Терплю.

За 24 км до города встретил машину с грибниками. Попросил воды. Флягу сразу выпил, а одну зарядил водой. Поблагодарил. Подсказали как доехать до города. За два часа --- три ведра грибов, вот такой у них "улов". Посмотрел и белые у них тоже есть.

Проехал и через некоторое время в пот бросило. Это от только что выпитой воды. Вот он рядом, виден город и так ещё далеко --- ехать и ехать. 

В 22.30 въехал в черту города. Остановили меня таксисты, очень разговорчивые и компанейские. Спрашивают, а я отвечаю: "Еду с Магадана и подскажите, как проехать на улицу Советскую?" "А сколько у тебя денег?" --- ещё один вопрос. "15.000 руб." --- ответил коротко я. Они сразу без лишних слов все свои трудовые собрали в кепку и дали мне. Сначала я отказывался, но потом по выражению их лиц я понял, что этим я их очень обижу. Взял, поблагодарил. Оказалось 4.225 руб. Один даже с Таллина был. Валентин Соболь --- 1000 руб, Сергей Сыздыков --- 1000 руб., Андрей Чукалин --- 1000 руб., Пётр Балдин --- 225 руб., Виктор --- водитель машины такси "41-65 СКА". После этого они решили довезти меня до улицы Советской. Они ехали впереди, а я следовал за ними по улицам Петропавловска. Потом предложили мне заехать в рабочий посёлок к Сергею Сыздыкову домой и переночевать там, а утром я поеду до своей улицы. Я согласился.

Сергей живёт в большом, частном доме. Нас встретила жена Сергея --- Света. Дома был сын Саша и десятимесячная дочка Настенька. Дом чистый, обширный, уютный. Умылся, поел и повалился спать. Усталость взяла своё и я быстро уснул.

***За день --- 215 км. Ок. --- 7394 км***
 