# На Нарву. Последние вёрсты {#Narva}

## 29.08.1993 г. воскресенье {#Narva-29-08-1993}

В 7.00 встрепенулся и продолжил спать.
Встал в 8.00. Чай зверобой --- три стакана с батоном и чесноком.

Ночью, похоже, дождь поливал. Собрался. Поблагодарил ребят за приют и внимание. В 10.05 выехал. Первый перекрёсток, налево поворот на Мойку, а мне прямо. 
Радоли, Жиглицы, проезжаю по мосту, под которым железная дорога, ведущая с Санкт-Петербурга на станцию Дно. Проехал Новгородскую область и въехал в Ленинградскую область. После 42 км пути решил перекусить. До Луги 15 км. 

Подкрепившись, в 13.20 продолжил движение на запад, к морю.  
Промелькнули Вычелобок, Берег, Подгородье, Крюково, Заклинанье.   Въехал в Лугу. В Луге есть памятная плита большевику, пламенному агитатору Толмачёву (1885-1919 гг.)

> *Здесь шли кровопролитные бои во время войны. Был создан Лужский рубеж, чтобы преградить путь врагу на подступах к Ленинграду.  
Памятная доска Герою Советского Союза Петровой.  
На 135 км трассы М-20, есть памятный комплекс павшим партизанам павшим под Лугой:  
"Вам сильные, гордые духом, мужественно пронёсшие Знамя Свободы по тылам врага".  
"Вам, непокорённые, не ставшие на колени перед фашизмом герои партизанских сражений под Ленинградом, Псковом, Новгородом".  
"Вам, бесстрашные партизаны, грудью преградившие врагу дорогу на Ленинград от благородных потомков".*

Поворачиваю с трассы М-20 налево, на Толмачёво. Дорога сносная, шоссе и не такая оживлённая. Доехал до пионерского лагеря "Олимпиец". Рядом полянка, на ней скамеечка, спортплощадка. Тепло и тихо, просто благодать. Время обеденное -- 15.20, сел на скамеечку и перекусил. 

В 15.50 продолжил свой путь.  
Мелькают деревеньки, дачи и пруды. Места красивые, приятные, живописные, расположенные к тому, чтобы тут человек мог полнокровно отдохнуть, набраться сил. Просто места для строительства санаториев, домов отдыха, пансионатов и пионерских лагерей. Повстречал на дороге грибников, "улов" хороший, не скроешь --- корзина то полная! 

У деревни Красные Горы ещё один памятник-обелиск:
"Партизанам-испанцам 1941-1945 гг."

Проехал деревеньки с интересными названиями: Высокая Грива, Поля, Шелопино, Черенская, Заходня, Броды, Любожачье, Сара-Лог. Вот и Осьмино появилось. Здесь, пожалуй, на ночлег останавливаться придётся.

На встречу мне ехал мотоциклист, которого я  решил остановить и спросить, где здесь можно остановиться на ночлег. После, как остановил его я представился, а потом и познакомился. Его звали Игорь. Ответ был безутешным и я поехал к центру посёлка.

Там я наткнулся на здание, в котором было отделение милиции. Зашёл в дежурку, а за столом сидел прапорщик, читающий газету. Я представился и спросил, где бы мне переночевать.
Тут такое удивление на лице у прапорщика: он то на меня, то в газету смотрит и в недоумении каком то спрашивает:" А это про вас тут в газете пишут?"

Я развенул газету и увидел себя, со своей "перламутровой девяткой", стою у речки Суры, в Пензе. 

"Да" --- коротко сказал я. А для прапора это было, как отмашка к действию. Он быстро сориентировался, позвонил куда надо и посоветовал идти прямо в столовую, которая была рядом. Здесь в общежитии живут студенты, которые приехали помочь собрать урожай корнеплодов и сейчас у них ужин. Велосипед оставил в отделении милиции, а сам пошёл в указанную столовую.

Пришёл в общежитие, где меня уже ждали. Сразу отвели в столовую, а после ужина уже разместили в общежитии.  

Ещё была просьба рассказать студентам про свой велопробег. После небольшой паузы, я коротко рассказал о своём вояже и ответил на многочисленные вопросы, которые посыпались сразу после рассказа.   Наиболее активным я дал визитки завода "ЗИФ". Необошлось и от тёплых пожеланий.  

Перед сном помылся на колонке холодной водой. Кровь сразу зациркулировала и тепло пошло по телу. 
Наметил на завтра маршрут. Хочу доехать до Кохтла-Ярве. Это примерно 166 км. Там живёт мой одноклассник: Вова Дмитриев, строитель и по совместительству заядлый шахматист.

***За день ---  128 км. Ок. --- 11049 км***

## 30.08.1993 г. понедельник {#Narva-30-08-1993}

В 7.00 подъём. Завтрак в столовой. Две порции рисовой каши навернул, два бутерброда с шоколадным маслом, запил чаем и был готов крутить колёса. А ведь ехал, вспоминал про масло и вот награда. Поблагодарил всех за внимание и отзывчивость. После крепких рукопожатий я отправился в отделение милиции за велосипедом. Рукопожатие с коллегами и в 8.30 я был в седле.  

Дорога хорошая, асфальтированная. Пошли деревни Редкино, Мышкино, Берег, Извоз --- подстанция на реке Вруда, Устье на речке Сумка. 
Далее Волпи, Морозово, Беседа, Крюково, Ястребино, Торма, Пустомержа. Железнодорожная станция Веймари, остановка Брюмбель, Ямсковицы и я вышел на трассу Ленинград-Таллин! До Кингисеппа 13 км. 

В 13.00 я был уже в Кингисеппе. Завернул на улицу Воровского, чтобы навестить свою сокурсницу по физинституту  Машу Вышемирскую. Дома был только сын Андрей, через которого я передал ей привет. Андрей угостил меня помидорами и яблоками. После небольшого отдыха я поблагодарил Андрея и поехал дальше.

В 15.30 я заехал в администрацию города Кингисепп, где мне поставили печать в журнале и пожелали удачи. Кингисепп -- это бывший Ямбург, а до этого именовался просто Ям. Ям равнялся примерно 22 км, где и меняли лошадей. До Ивангорода ровно один ям, но ни я и не меня никто менять не будет. Мне останется протянуть свою лямку ещё 220 км. А пока я в Кингисеппе. Проехал мост через реку Луга. Ещё немного и граница.  

Приехал в Ивангород, последний российский город на моём пути.  
Заехал на почту. Дал телеграмму отцу. Настроение --- приподнятое.  
Отправился на таможню. Прошёл без задержки. Фото на память в Нарве.   
Еду до Силламяэ без остановок. Там живёт Лёва Загжецскас и его семья. Он член сборной Эстонии по лёгкой атлетике. Неоднократный чемпион Эстонии на средние и длинные дистанции. Дважды выигрывал престижный пробег вокруг озера Вильянди. Мы часто вместе были на сборах, тренировались и выступали на многих соревнованиях. Очень ответственный, трудолюбивый, с чувством доброго юмора спортсмен.  

17.00 я прибыл в Силламяэ. Сразу еду на улицу Зелёную, где проживает Лёва. Но он переехал на улицу Чкалова. Еду туда. Все дома. Жена Ирина, Лёва и две дочери Лена и Кристина. Неожиданная и тёплая встреча. После душа сели за стол и продолжили наши воспоминания о былом и насущном. Уснули за полночь.

***За день --- 151 км. Ок. --- 11200 км***

## 31.08.1993 г. вторник {#Narva-31-08-1993}

В 6.00 подъём. Ирина оладьи испекла. Чай с оладьями и вареньем. Поблагодарил друзей и в путь. Сегодня надо до Таллина дотянуть. Лёва проводил да трассы, она рядом в 100 метрах от дома. В 7.00 я выехал.  

Быстро доехал до Кохтла-Ярве. Заехал на улицу Лехе. Но там тех, кого мне сказали навестить не оказалось, так как переехали на новое место жительства. Это я выполнял наказ Осиповой Антонины, который она дала мне перед выездом с Сокола. Там проживали её далёкие родственники. Жаль что не смог выполнить наказ.  

Теперь я должен заехать к школьному другу Володе Дмитриеву.  
Подъехал к дому. Поднялся. Звоню. Стучу. Никто не отвечает. Жаль. Придётся ехать в Таллин. Там живут родители Володи, в 100 метрах от моего дома.  

Поехал дальше. Ещё 150 км до Таллина. День чудесный, солнечный.  
Настроение приподнятое. Сегодня буду дома. Друзей увижу.  
Соскучился.

Вот проезжаю интересное место. Высокий глинт, с которого открывается великолепный вид на залив. 132 км от Таллина. На краю обочины стоит старый крест. С этого места в хорошую погоду на горизонте можно увидеть четыре острова. Вот и сейчас погода благоприятствует этому. Перекусил

Проехал всего один километр и вижу на встречу едут два велосипедиста. По мере приближения понял, что это девушка и парень, оба иностранцы. Встретились в 9.55. Познакомились. Её зовут Кристи Штутц, она американка. Его зовут Крис Галум, он с Австралии. Они путешествовали по Европе и едут в Ленинград. Сказал им, что это мой любимый город, а сегодня у меня последний день моего путешествия. Подарил им российскую монетку на память. Пожелали друг другу хорошей дороги и на этом расстались: разошлись как в море корабли.

Проехал три часа, очередной привал, но уже на остановке. До Таллина 93 км. Даёшь Таллин! Фляжку чая опустошил. Вперёд. Солнце светит славно, а вот ветер усилился, правда хорошо боковой -- норд. С моря дует. Свежачок.И мне пора ехать, на часах 13.30.

Заехал в Вийтна. 73 км осталось. Позвонить не могу с узла связи. Пошёл в корчму. Там разрешили позвонить. Звоню своему школьному другу Володе Бань. Он предлагает заехать к нему домой, как въеду в город. Позвонил и одноклассникам Андрею и Ангелине Греци. Тоже зовут к себе, но это уже после Володи.

> *День!  
Вот он наступил, Заревой!  
Последний день --- он самый, самый.  
Последний на этом пути Магадан --- Таллин.  
От моря до моря.  
А море уже видно*
  
Вот до датского городка надо добраться.  

Проехал озеро Марду. Заехал в Ласнамяэ к Володе Бань. Приятная и догожданная встреча с друзьями. Дома были жена Аня и дети Володя и Илья. Поблагодарил друзей и поехал дальше домой.  

Приехал домой! Успел! Завтра в школу. 1 сентября. Буду работать в школе №52 преподавателем физкультуры младших классов.

***За день --- 201 км. Ок. --- 11401 км***

**Мои девизы, с которыми я преодалел велопробег Магадан --- Таллин**:

1. Динамо -- это сила,  
   Сила в движении,  
   А движение --- это ЖИЗНЬ!
2. Человек --- не стой,  
   Стояние на месте --- смерть.  
   Сделай первый шаг.
3. Бороться и искать, найти и не сдаваться.
4. Лучше гор могут быть только горы,
   На которых ещё не бывал.
5. Колыма, Север, Сибирь --- шутить не любят, 
   Недооценка чпевата последствиями...
6. Дорогу осилит идущий.
7. Вера, Надежда, Любовь.
8. Мой адрес не дом и не улица, 
   Мой адрес Советский Союз.
9. Я там, где плакаты "ВПЕРЁД!"
10. У природы нет плохой погоды.
11. Старость меня дома не застанет
    Я в дороге, я в пути.
12. Счастлив тот, кто устал в пути
    Сто дорог готов пройти...
13. Я счастлив и нем и только немного                         
    Завидую тем, другим, у которых всё
    Это ещё ВПЕРЕДИ!
       
**С 22.08.1992 г.по 14.11.1992 г. проехал 6795 км = 85 дней  
Затраты = 4.879 рублей. Помощь = 16.200 рублей  
с 19.07.1993 г.по 31.08.1993 г. проехал 4606 км = 44дня
Общий км = 11401км = 129 дней
Затраты = 9058 рублей. Помощь = 10.725 рублей.  
за 129 дней затраты = 13937 рублей и помощь = 26.925 рублей.  
12 бань.  
30 спиц.  
10 покрышек.  
Ни одного прокола! только грыжи были --- выпирало.**  