---
title: "Путешествие из Магадана в Таллин"
author: "Сергей Лыжин"
lang: "ru"
site: bookdown::bookdown_site
output: bookdown::gitbook
mainfont: "Times New Roman" #Georgia #"Palatino Linotype"
monofont: Courier New
monofontoptions: Scale=0.7
fontsize: 12pt
papersize: a4
classoption: oneside
geometry:
- top=20mm
- left=25mm
- right=15mm
- bottom=20mm
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: dvesti/0
url: "https\\://https://dvesti.github.io/0/"
description: Путешествие на велосипеде
header-includes:
- \usepackage{fontspec}
- \usepackage{indentfirst}
- \setlength\parindent{10mm}
documentclass: book
---

# По Золотой Теньке {#index}

## 23.08.1992 г. воскресенье

Встали.
Дождь на улице, а я хотел сегодня до Мадауна доехать.
Планы меняются.
А сколько таких ситуаций будет у меня в пути?
Путь-то немаленький, но на этом сейчас не зацикливаюсь.
Исходить надо из сложившейся ситуации в данный момент и смотреть на всё реально.
А пока попьём чаю с Сашей.

К 12.00 дождь прекратился.
Доеду до Сокола, а там решу: ехать дальше или останусь ночевать у друзей.
До Палатки есть, где остановиться.
Друзья всегда выручат.

12.20 мы с Сашей вышли из дома на шоссе, пожали руки, обнялись и я поехал в сторону аэропорта, в посёлок Сокол.
Трасса великолепная, ровно бежит мой велоконь.

Проехал посёлок Снежный, где расположена наша динамовская база.
Cюда на первый снег приезжала сборная СССР по лыжам.
Легендарные: Смирнов, Девятьяров, Ордина, Лазутина и другие, а для Елены Вяльбе (Трубицыной) эти места --- родные.

На перевале Хабля поморосило, на то и есть перевал: там ближе к облакам.

> *Помню: дежурил я на Соколе под Новый год. Поступил звонок с УВД г. Магадана: срочно выехать на бытовую кровавую разборку. Беру машину и --- быстро на перевал. Приехали. Со всеми мерами предосторожности ворвались в дом. А там один уже лежит с окрававленной ногой. Объясняет нам, что убежал обидчик.  
Где искать? Мороз под 30.  
Помощник с водителем остались, а сам --- на двор.  
Фонарём посветил и увидел кровавый след, ведущий к сараю.  
Вынул пистолет и --- туда.
Там никого, а след ведёт дальше по тропинке, между кедровым стлаником.
Тропинка кончилась, а дальше наст. Но он: где держал убежавшего, а где проваливался. Понял, что далеко не ушёл. Преследовать стал, а сам тоже проваливаюсь.  
Вдруг увидел в 30 метрах тёмный холмик на снегу.  
Кричу: «Руки вверх, а то стрелять буду!» В ответ --- тишина.  
Стал по насту к нему перекатываться.
Осветил его, а он и не шевелится. Замерзать стал. Убегал в том, что было на себе.  
Сдали его дежурному по УВД.  
Вот такая история с этим местом в памяти осталась.*

Вот и Уптар.
7 км до Сокола.

> *Когда работал в Соколе, то здесь я выходил из автобуса и бежал до своего медвытрезвителя.  
Помню: вышел из автобуса в один из самых холодных дней (-52 градуса было на градуснике) и --- побежал.  
Вот, где спёрло дыхание!  
Закрыл рукавицами лицо и постепенно, маленькими порциями, вдыхал в себя колючий воздух.  
А ветровка колом встала и так громко шелестела при взмахе рук, как будто она разрывается.*

Показался Сокол, на часах 15.00, 50 км проехал.
Поворачиваю направо, проезжаю мимо медвытрезвителя, где когда-то работал начальником.

> *Рядом дом, где живёт Колесник Владимир, с которым вместе работали.  
Добросовестный, исполнительный и надёжный милиционер. 
Хорошее подразделение было. В 1990 году, ещё в Советском Союзе, я купил за 90 рублей велосипед "ЗИФ" (завод имени Фрунзе) Пензенского велосипедного завода! Этот завод --- родина моей «перламутровой девятки». Магазин был в 100 метрах от медвытрезвителя. Когда купил, встал вопрос, где оставить моего «коня». Вот тогда Володя меня и выручил: поставил к себе в сарай до 1992 года.*

Заехал к Володе.
Дружная семья и всегда тепло встречает.
Сразу за стол пригласили и накормили.
Поделился планами.
Поблагодарил и далее поехал к коллегам, на пульт вневедомственной охраны.

Вот первым встретил Славу Руденю.
Настоящий друг, спортсмен, заядлый футболист.
Организатор многих футбольных турниров на Соколе.
С ним попили чайку, поговорили о моём предстоящем путешествии.

Вдруг дождь нахлынул, не перестаёт, а только усиливается.
Заехал к хорошим моим друзьям: Антонине и Николаю Осиповым.
У Николая отец с Архангельска, земляк.
Тут, уж, они меня никуда не отпускают.

Остаюсь на Соколе.
Они тоже коллеги --- работают во вневедомственной охране.
Тёплый вечер под дождичек, с приятными и добрыми воспоминаниями продолжился до полуночи.

***За день --- 50 км. Ок --- 55 км***

## 24.08.1992 г. понедельник

Утро.
Встали.
Вместе позавтракали.
Погода прекрасная.
Солнышко светит, лёгкий ветерок.
Все, кто был свободен по службе, проводили меня в дальнюю дорогу.
Фото на память и вперёд на Палатку.

Мчусь по хорошей дороге, по асфальту, но это удовольствие только до Палатки.

Проехал Стекольный, Хасын.

Вспоминаю свои этапы в эстафете (пробеге) Мяунджа -- Магадан, посвящённой Дню Победы.
Организатором этих пробегов был Барканов Владимир Никанорович, председатель клуба любителей бега (КЛБ "Айсберг-700") города Магадана.
Замечательный, справедливый, деловой, принципиальный, трудолюбивый спортсмен.

Вот проезжаю ручей Красавица.

> *Здесь был последний мой этап, который определил победителя пробега 1989 года. Сам Барканов был фаворитом и многие решили, что он и стал победителем. Он лично пересчитал результаты по этапам и объявил меня победителем. Он был жёстким, но справедливым. Всего 20 секунд решило судьбу первого места. Он первым пожал тогда руку. Уважаю этого мужественного спортсмена.*

Вот и проскочили два часа моего прогона до Палатки.
Проезжаю мимо постамента, на котором замер МАЗ с надписью по-ниже: «Автомобилю-труженику 1933-1983».
Работяги давали стране «угля»!

Сворачиваю на улицу Ленина, где живёт Суворов Саша.
Саша и жена Катя --- дома.
Застал.
Попал прямо на обед.

> *Саша превосходный лыжник и бегун. Мы с ним участвовали во многих соревнованиях и пробегах. Терпеливый и серьёзный соперник.*

После обеда он тут же подготовил мне чай в дорогу, на травах и с лимонником.
Поблагодарил и --- в путь.
Спешить надо, уже отстаю от графика, который наметил себе.

> *Вспомнил слова Саши Богданова, с которым жили вместе в комнате общежития на Кольцевой: «Сергей, на трассе уже выпал снег и конкретно --- на Яблоневом перевале».*

При выезде с Палатки заехал в дежурную часть Хасынского РОВД.
В 13.40 поставил печать в мой бортовой журнал дежурный Майструк Н.Н.
и я снова --- в седле.

Проехал посёлок и кончилось шоссе.
Повернул налево на Тенькинскую трассу, которая «*золотою Тенькою*» зовётся.
Велосипед идёт хорошо.
Машин мало.
Мелькают сопки, на некоторых просматриваются горизонтальные полоски --- это козьи и бараньи тропы.

> *Во время войны эти животные тоже внесли свой вклад в победу, если так можно выразиться. И шерсть и мясо были очень необходимы для фронта.*

18.00.
Вот и первый хороший подъёмчик.
На вершине перекусил.

19.00 в посёлке Мадаун.
Проехал не останавливаясь.
Вот первая существенная река Армань.
Мост большой, справа рабочие домики дорожников.

Смеркается.
Спешу.
Вот --- и темнота пришла.
Никакого жилья.
Вот --- заброшенный посёлок Мукульчан.
Слева домик маленький.
Он один жилой остался.
Постучался и --- пустили.
Здесь живёт Мешков Михаил Юлианович.
Ему 68 лет.
С ним живёт ещё бабка, как он сказал, и она -- отдыхает.
Он живёт в этом посёлке с 1946 года.
В Эстонии воевал, дошёл до Германии.
Вот какие встречи меня поджидают.
И это --- только начало.
Всё, что меня интересовало, я старался с первых уст записать в свой дневник без прикрас, как сказано было первоисточником.
У меня была пол-литра водки и сигареты.
Это Саша Томашевский посоветовал взять с собой на всякий случай.
Мало ли что?
Вот и Михаил спросил меня: «*Нет ли у меня чего?*» Я достал водку, налил ему рюмочку и дал пачку сигарет.
Дед был очень рад такому сюрпризу.
В свою очередь он предложил покушать: «*В подсобке, на холоде, стоит кастрюля горохового супа. Возьми сколько осилишь и подогрей.*» Пригодились Сашины сухарики.
Размочил в миске и всё это заел луком.

> *Лук или чеснок у меня всегда был, поэтому, наверное, я никогда не простывал. Это совет тем, кто отважится на что-то подобное. Верное средство! Проверено на себе.*

После супа напился чаю!
За чаем я спросил Михаила про трассу, что меня ждёт дальше, хотя я по этой трассе и бегал и проезжал по службе несколько раз.
Посёлок Палатка стоит на трассе с «0» км, если ехать по Тенькинской трассе в сторону Якутии, как я и поехал.
Мукульчан стоит на 106 км от трассы.

> *Примерно через 10 км будет «долина смерти». Здесь в своё время шёл конвой с заключёнными. Поднялась метель. Поступил приказ: «Прилечь!» Метель долго не прекращалась. Так всех и замело. А уже после, весной, нашли эти «подснежники».*

«*Далее будет крупный посёлок --- Усть-Омчуг, а перед ним перевал Гусакова*» --- добавил дед.
За продуктами надо ездить в Мадаун.

> *И ещё совет: где бы вы ни были, если есть вода, даже ледяная, --- сделать омовение. Только эту процедуру сделать быстро, избегая переохлаждения. Гигиена --- в первую очередь.*

Вот и тут, перед сном я спросил у Михаила, где можно помыться.
«*Только на ручье в 20 метрах от дома*», --- был ответ.
Я вышел, дошёл до ручья с кристально-чистой, холодной водой и быстро освежился.
Тут же вытерся, оделся и забежал в дом.
Поблагодарил Михаила и пожелал ему приятного сна.
Мы тут же уснули.

***За день --- 138 км. Ок --- 193 км***

## 25.08.1992 г. вторник

Встали.
На дворе --- хорошо моросит.
Попили чаю.
Жду.
12.00.
Ещё раз поблагодарил Михаила и отправился в путь.

Вот и «долина смерти» слева, до 120 км.
Далее ручей, мост, на котором остановился и перекусил, попил холодного чая.

Пролетел милицейский уазик в сторону Усть-Омчуга.
Я ещё в дежурке был осведомлён, что завтра с проверкой поедет С., проверяющий, с которым я знаком.
Отношения между нами "ровными" назвать нельзя, поэтому он и проехал не останавливаясь.
Даже водитель припустил, когда поравнялись.
Команда была дана.
А в окне было видно, как сверкало его личико.

На 126 км повстречалась лисичка, которая, косо поглядывая на меня, переминала лапками.

130 км --- перевал Гусакова.
Фиксирую этот факт на фотоаппарат.
А теперь спуск и через 10 км "дистанция 141 км" --- это дорожники стоят, поддерживают трассу в рабочем состоянии.

Пролетаю "дистанцию --- 169 км".

Вот проезжаю место большой трагедии.
"Вахтовка" сгорела, двери заклинило.
Остался только корпус ржавый.
Остановился, постоял минуту.

В 16.20.
Докатил до Усть-Омчуга.

В дежурную часть Тенькинского РОВД заехал.
Дежурный старший лейтенант милиции Данько поставил печать и я был готов ехать дальше, но встретил коллегу Поддубняка, с которым бежали кросс в посёлке Ола на 9 км и 1 км.
Вспомнил.
Молодец!
И сейчас помог выбраться на тенькинскую трассу, чтобы не плутать.

На 187 км трассы перекусил у речки.
Дождичек переждал и в 19.00 продолжил свой путь.

Оторвался багажник на переднем колесе.
Перетянул жгутами и снова в путь.

На 195 км мчится джип в мою сторону.
Пролетел меня и остановился.
Возвращается.
Ну думаю: зачем я им?
Присмотрелся, а это наш коллега Витя Федоренко.

> *Мы знакомы через Володю Пономаренко, тоже коллега по службе, и хороший товарищ, очень внимательный и чуткий человек. Там я поделился своими планами... Вот он меня заметил и вернулся.*

"*Ну, что, решил?*" --- спросил он.
"*Да, решил. Надо ехать, уже осень на носу, надо спешить!*" "*А сколько денег взял?*" --- допытывается Виктор.
"*Двадцать пять тысяч!*" --- ответил ему я.
"*Этого мало и до Москвы не хватит! На возьми, у меня пока есть*" -- подаёт мне Виктор 10.000 рублей!
Поблагодарил его и на этом мы разъехались в разные стороны.

> *А видел я Виктора в гостях у Володи всего два раза. Даже сейчас расстались, а я не знал как его величать. Ехал и долго вспоминал его имя и фамилию. Вспомнил --- Виктор Федоренко. Видно проникся и поверил в мои планы. Я всё отметил в журнале --- как было.*

Мчусь.
Взял Нелькобинский перевал, спуск и в 21.50 был в Нелькобе.
Дождь застал меня в пути.
Промок.
Сразу стал искать место для ночлега.
Зашёл в дом для приезжих, который раположен на улице Школьной.
Там послали к главе посёлка, дали телефон.
Позвонил Анне Николаевне.
Получил отказ.
Пошёл к ребятам в общежитие.
Спасибо приютили.
Это были Александр Николаевич и Владимир Петрович.
Быстро в душ.
Согрелся, постирался.
Поужинал.
Поделился своими планами.
Сон в 1.00.
А ребята всю ночь курили и пили.
До 3.20 это продолжалось.
Наконец-то свет погас.
Оказывается, где-то провода порвались, замкнуло.
Снегу навалило.
Просыпался несколько раз.
Ребята рыбачить приехали, им-то что?
Могут и отложить рыбалку.
А мне-то ехать.
Вот они и смеялись: "*А как турист утром поедет?*"

***За день --- 132 км. Ок --- 325 км***

## 26.08.1992 г. среда

В 6.20 подъём.
Все спят.
Вышел на улицу.
Снега!
И --- лёгкий морозец.
Вернулся в комнату.
Лежал.
Светлее стало.
Пора.
Собрался и на выход.
В 8.15 выехал.
Хорошо: снег свежий и сырой.
Велосипед едет, а за мной жирный след от колёс отпечатывается на дороге.
Хоть бы машина проехала, а то еду по целине первый.
Лиственницы повисли словно дуги.
Проезжаю под ними, как под арками.
Будто девчата хороводят и платочками машут.
Всё в снегу, сказочная картина получается.
Снежный тоннель, как труба длинная.
Вот и машина прошла мимо меня.
В кузове народ сидит и громко обсуждают увиденное.
Теперь еду по-машинному следу.
Легче.

Проехал 25 км.
Ноги замерзли.
Снег на ногах тает и превращается в холодную воду.
Холодит.
Пришлось остановиться, снять носки с одной ноги и спустить штаны.
Приложил голую стопу одной ноги к ляшке другой ноги.
Стоял, словно цапля на болоте.
Активно стал растирать и массировать руками закоченевшую стопу.
Кровь побежала, пальцы зашевелились.
Ту же процедуру проделал с другой стопой.
Никого нет, стесняться некого.
А перед тем, как носки натянуть на ноги, надо их продуть тёплым воздухом своих лёгких, как лыжники поступают перед стартом, когда мороз.
И ещё проделывал такое упражнение: активно сжимал и разжимал пальцы на ноге пока не придёт потепление.

Вот и посёлок Транспортный появился.
Перед посёлком глухарь вспорхнул.
Опять поломка.
У багажника болт вылетел.
Починил.
В посёлке столовая работает.
Зашёл и теплом обдало.
Откушал на 56 рублей.
Солнышко вышло.
Разомлел в столовке, но надо спешить.
Снег стал на трассе таять, а на сопках уж до весны останется.
Ветерок встречный меня обнимает.
Настроение улучшается.

Проезжаю Гастелло, Омчак.
Замерзать опять начал.
Вот и Кулинский перевал пошёл.
Надо подкрепиться: пирожки с чаем и вперёд.
Круто, поэтому вверх пешком, заодно и ноги разогрею.
На вершине, теперь спуск.
Вниз быстро качусь.
Тряска хорошая, вот и сварка на багажнике отвалилась.
Перетянул и дальше еду.
Кулу, бензоколонка.
Вот и мост через реку Кулу.
Солидный мост и река полноводная.

Подъехал к "дистанции --- 118 км", посёлок Нерючи.
На часах 19.15.
Стоит барак.
Люди ещё живут.
На глаза попал юноша.
Зовут его Владислав.
Расспросил его, где можно багажник починить.
Он отвёл меня в мастерские и там сам стал решать мой вопрос.
А меня отвёл к себе в семью.
Семья большая.
Тётя Тамара, мать Алина, сёстры Елена, Анюта и брат Антон.
Принял душ с дороги.
Согрелся.
С Владиславом сходили в магазин и отоварился там на 156 рублей.
Взял два фарша рыбных, горох, масло 300 грамм, сгущёнку.
Все вместе поужинали.
Сгущёнка быстро ушла, сходил ещё за одной.

> *Видно дети тоже кушать хотят. Посёлок закроют, работы нет. Куда с детьми? Удручающая картина. Это всё последствия развала большой державы. Вот оно всё на виду. Политики эту семью в расчёт не брали.*

Владислав пришёл поздно с мастерских, но багажник приварил.

> *Спасибо тебе, Владислав Николаевич Клин. Рано ты повзрослел. Он постоянно встаёт перед моими глазами. Где они? Что с ними? Только тот адрес, что он написал и остался. Я дважды проезжал это место, но жилья никакого там нет.*

Большая, бедная семья, а приняла меня, путника с дороги, как своего.

***За день --- 117 км. Ок --- 442 км***

## 27.08.1992 г. четверг

Подъём, попил чаю.
Поблагодарил Алину, а с Владиславом пошли до развилки.
Указатель: налево дорога на прииск имени Марии Расковой, а мне прямо --- на Кедровый.
Сфотографировались с ним на память.
Пожал руку парню и поехал.
Было 10.15.

Добрался до Матрайбыта.
Обед: курица.
14.00.
Встретился с водителями: Володя с Кадыкчана!

> *Он вёз меня с Кедрового 1 июля в этом году. Вот так встреча. Тесно на Колыме!*

Вот подъехал к подножью перевала "Гаврюшка".
Пришлось слезать и пешком подниматься, скорость то одна.
Вот и вершина!
Красота!
Сопки все в снегу.
Проезжал на удачу мотоциклист.
Остановил его и попросил сфотографировать меня на фоне сопок.

> *Вышло хорошо. А то всё бегом или на машине. Не полюбуешься по-настоящему этими красотами. Не проникнешься, не прочувствуешь простор, охват, что глаз видит.*

Теперь на спуск --- более 10 км!
Спустился, долину проехал и опять на перевал -- "Лачкалах", так зовётся он.
Взял его и на спуск... Быстрее надо.
Темнеет.
Добрался до посёлка Каменистый.
Замечательная столовая там.
Борщ --- отменный.
А хлеб!
Брали и покупали в дорогу.
Горяченький, сдобный, душистый!

Не останавливаюсь, жму до Кедрового, где ЛТП (Лечебно-трудовой профилакторий) расположен.
Доехал.
23.15.
Темно.
С дежурным переговорил.
Представился.
Запустили.
Устроился.
Холодно, ещё не отапливают.
Подогрели воду, помылся, постирался.
Отужинал и после вели беседу до 3.00 ночи.
Холодно ночью, четыре одеяла на себя натянул.

***За день хорошо поработал --- 158 км. Ок --- 600 км***
